// M25-21 per-command hardening on the REAL integrated shell (`frontend/e2e/nleShell.tsx`): the
// same real session, binding and overlay a user drives, answered by the real canonical core.
// Every one of the 34 canonical commands gets its own accessibility case and its own recovery
// case; the coverage manifest (`governance/contracts/nle_hardening_coverage_manifest_v1.json`,
// generated by `scripts/nle_hardening_manifest.py`) names these exact titles.
//
// Accessibility: the control the recipe is about to press is the manifest's control by role and
// accessible name, a hit-testable target of at least 44 x 44 CSS px, reachable by keyboard focus;
// a real tap then issues exactly one command of the row's kind, the accepted revision is announced
// in the live timeline status, and focus stays on a connected element inside the editor.
//
// Recovery: the core accepts the command and its reply is lost on the way back. The session must
// report the outcome as unknown (never rejected), reconcile with exactly one read-only history
// read, adopt the core's accepted state without replaying anything, keep focus in the editor, and
// let the next explicit command proceed on the reconciled base.
import { test, expect, type Locator, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";

import {
  CONCURRENT_CLIP,
  CONFLICT_COPY,
  Counter,
  TIMELINE_STATUS,
  commandRecipes,
  press,
  probeNextActivation,
  type Recipe,
} from "../helpers/nleCommandRecipes";
import { Checks, hardeningEvidence } from "../helpers/nleHardeningEvidence";
import {
  openIntegratedShell,
  shellSnapshot,
  shellSurface,
  type ConcurrentEdit,
} from "../helpers/nleShell";

test.use({
  viewport: { width: 1440, height: 900 },
  deviceScaleFactor: 1,
  hasTouch: true,
});

type CommandRow = Readonly<{
  command: string;
  operation_id: string;
  control_selector: string;
  role: string;
  accessible_name: string;
}>;

const MANIFEST = JSON.parse(
  readFileSync(
    new URL(
      "../../../../governance/contracts/nle_hardening_coverage_manifest_v1.json",
      import.meta.url,
    ),
    "utf8",
  ),
) as { command_rows: CommandRow[] };

const { recipes, select, settled } = commandRecipes(shellSnapshot);
const PENDING_COPY = "Applying command…";
// B-M1605-COPY-01: a refused edit says it was not applied; a failed request says it did not complete.
const REJECTED_COPY = ["not applied", "did not complete"] as const;

/** HH:MM:SS:FF at the composition's fixed 24 fps, computed here rather than by the product. */
function timecode24(frame: number): string {
  const pad = (value: number) => String(value).padStart(2, "0");
  const seconds = Math.floor(frame / 24);
  return `${pad(Math.floor(seconds / 3600))}:${pad(Math.floor(seconds / 60) % 60)}:${pad(seconds % 60)}:${pad(frame % 24)}`;
}

/** `{clip}`-style placeholders in a manifest name match any clip label; ` / ` separates edges. */
function accessibleName(template: string): RegExp {
  const alternatives = template.split(" / ").map((part) =>
    part
      .split(/\{[^}]+\}/)
      .map((literal) => literal.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
      .join(".+"),
  );
  return new RegExp(`^(?:${alternatives.join("|")})$`);
}

/** The rebase row needs a real refusal first: another client's edit lands before the browser's. */
function conflictOnce(kind: string): ConcurrentEdit {
  let done = false;
  return (transaction, index) => {
    const commands = transaction.commands as { kind: string }[];
    if (done || commands[0]?.kind !== kind) return undefined;
    done = true;
    return {
      ...transaction,
      request_id: `concurrent-${index}`,
      transaction_id: `tx-concurrent-${index}`,
      commands: [
        {
          kind: "set_clip_enabled",
          payload: { clip_id: CONCURRENT_CLIP, enabled: false },
        },
      ],
    };
  };
}

function concurrentFor(recipe: Recipe): ConcurrentEdit | undefined {
  return recipe.operation === "conflict.rebase"
    ? conflictOnce("set_clip_enabled")
    : undefined;
}

type Kinded = {
  commands: { kind: string }[];
  expected_timeline_revision: number;
};

function kinds(transactions: readonly unknown[]): string[] {
  return transactions.map(
    (transaction) => (transaction as Kinded).commands[0]!.kind,
  );
}

/** Where focus is, described without DOM references: inside the editor, on body, or elsewhere. */
async function focusPlace(page: Page) {
  return page.evaluate((surface) => {
    const active = document.activeElement;
    const dialog = document.querySelector(surface);
    return {
      connected: active !== null && active.isConnected,
      onBody: active === document.body || active === null,
      inEditor: dialog !== null && active !== null && dialog.contains(active),
      role:
        active?.getAttribute("role") ?? active?.tagName.toLowerCase() ?? null,
      control:
        active
          ?.closest("[data-h3-nle-control]")
          ?.getAttribute("data-h3-nle-control") ?? null,
    };
  }, shellSurface);
}

async function inspectTarget(
  page: Page,
  target: Locator,
  row: CommandRow,
  checks: Checks,
) {
  const facts: Record<string, unknown> = {};
  await checks.step("role_and_accessible_name", async () => {
    await expect(target).toHaveRole(row.role as "button");
    await expect(target).toHaveAccessibleName(
      accessibleName(row.accessible_name),
    );
    await expect(target).toHaveAttribute(
      "data-h3-nle-control",
      row.operation_id,
    );
  });
  await checks.step("target_at_least_44px", async () => {
    // A control below its pane's scroll fold is reached by scrolling, as a user would.
    await target.scrollIntoViewIfNeeded();
    const box = await target.boundingBox();
    expect(box).not.toBeNull();
    facts.target_width = Math.round(box!.width * 10) / 10;
    facts.target_height = Math.round(box!.height * 10) / 10;
    expect(box!.width).toBeGreaterThanOrEqual(44);
    expect(box!.height).toBeGreaterThanOrEqual(44);
  });
  await checks.step("hit_testable_at_its_center", async () => {
    const hit = await target.evaluate((element) => {
      const rect = element.getBoundingClientRect();
      const top = document.elementFromPoint(
        rect.left + rect.width / 2,
        rect.top + rect.height / 2,
      );
      const topRect = top?.getBoundingClientRect();
      return {
        matches: top !== null && (top === element || element.contains(top)),
        target: {
          left: rect.left,
          top: rect.top,
          width: rect.width,
          height: rect.height,
        },
        top:
          top instanceof HTMLElement
            ? {
                tag: top.tagName,
                className: top.className,
                control: top.dataset.h3NleControl,
                edge: top.dataset.h3NleTrimEdge,
                left: topRect?.left,
                top: topRect?.top,
                width: topRect?.width,
                height: topRect?.height,
              }
            : null,
      };
    });
    expect(hit.matches, JSON.stringify(hit)).toBe(true);
  });
  await checks.step("keyboard_focusable_outside_inert", async () => {
    const route = await target.evaluate((element) => {
      const outsideInert =
        element.closest("[inert],[aria-hidden='true']") === null;
      const toolbar = element.closest('[role="toolbar"]');
      if (toolbar === null || !element.hasAttribute("data-h3-nle-toolbar-item"))
        return {
          outsideInert,
          direct: (element as HTMLElement).tabIndex >= 0,
          current: -1,
          target: -1,
          count: 0,
        };
      const items = Array.from(
        toolbar.querySelectorAll<HTMLElement>("[data-h3-nle-toolbar-item]"),
      );
      return {
        outsideInert,
        direct: false,
        current: items.findIndex((item) => item.tabIndex === 0),
        target: items.indexOf(element as HTMLElement),
        count: items.length,
      };
    });
    expect(route.outsideInert).toBe(true);
    if (route.count === 0) {
      expect(route.direct).toBe(true);
      await target.focus();
    } else {
      // A roving toolbar intentionally has one Tab stop. Prove the named target is reached by
      // its owned ArrowRight path instead of requiring every item to violate the APG pattern.
      expect(route.current).toBeGreaterThanOrEqual(0);
      expect(route.target).toBeGreaterThanOrEqual(0);
      const toolbar = target.locator('xpath=ancestor::*[@role="toolbar"]');
      const items = toolbar.locator("[data-h3-nle-toolbar-item]");
      await items.nth(route.current).focus();
      const steps = (route.target - route.current + route.count) % route.count;
      for (let step = 0; step < steps; step += 1)
        await page.keyboard.press("ArrowRight");
    }
    await expect(target).toBeFocused();
  });
  return facts;
}

for (const recipe of recipes) {
  const row = MANIFEST.command_rows.find(
    (candidate) => candidate.operation_id === recipe.operation,
  )!;

  test(`hardening a11y ${recipe.operation} is a named 44px touch target that issues one ${recipe.kind} and keeps focus in the editor`, async ({
    page,
  }, testInfo) => {
    expect(row.command).toBe(recipe.kind);
    // Holds the row's own reply so the pending window -- the control that issued the command is
    // disabled until it settles -- can be observed.
    let gate: Promise<void> | undefined;
    const oracle = await openIntegratedShell(page, "smoke", {
      concurrent: concurrentFor(recipe),
      reply: async () => {
        await gate;
        return "fulfill" as const;
      },
    });
    const count = new Counter();
    const context = await recipe.prepare?.(page, count);
    const before = await shellSnapshot(page);
    const sent = oracle.transactions.length;
    const checks = new Checks();
    let targetFacts: Record<string, unknown> = {};
    probeNextActivation(async (target) => {
      targetFacts = await inspectTarget(page, target, row, checks);
    });
    let release = () => {};
    gate = new Promise((resolve) => {
      release = resolve;
    });
    let pendingFocus: Awaited<ReturnType<typeof focusPlace>> | undefined;
    try {
      await recipe.act(page, "touch", context);
      await checks.step("focus_held_in_the_editor_while_pending", async () => {
        await expect
          .poll(async () => (await shellSnapshot(page)).authoringStatus)
          .toBe("pending");
        pendingFocus = await focusPlace(page);
        expect(pendingFocus).toMatchObject({
          connected: true,
          onBody: false,
          inEditor: true,
        });
      });
    } finally {
      gate = undefined;
      release();
    }
    await checks.step("touch_activation_issues_one_command", async () => {
      await expect
        .poll(async () => (await shellSnapshot(page)).receipts)
        .toBe(before.receipts + 1);
      expect(kinds(oracle.transactions.slice(sent))).toEqual([recipe.kind]);
    });
    const after = await shellSnapshot(page);
    const revision = after.timelineSnapshot!.timelineRevision;
    await checks.step("accepted_revision_announced", async () => {
      const status = page.locator(TIMELINE_STATUS);
      await expect(status).toHaveAttribute("role", "status");
      await expect(status).toHaveAttribute("aria-live", "polite");
      // M25-63 (R9): the revision is an attribute, never text; the live region says "Saved.".
      await expect(status).toHaveAttribute(
        "data-h3-nle-timeline-revision",
        String(revision),
      );
      await expect(status).toHaveAttribute("data-h3-nle-save-state", "saved");
      await expect(status).toHaveText("Saved.");
      await expect(status).not.toContainText(CONFLICT_COPY);
    });
    const focus = await focusPlace(page);
    await checks.step("focus_stays_in_the_editor", () => {
      expect(focus).toMatchObject({
        connected: true,
        onBody: false,
        inEditor: true,
      });
    });
    await hardeningEvidence(testInfo).row(
      `command.${recipe.kind}`,
      "accessibility",
      checks,
      {
        ...targetFacts,
        via: "touch",
        revision_before: before.timelineSnapshot!.timelineRevision,
        revision_after: revision,
        focus_pending: {
          role: pendingFocus?.role,
          control: pendingFocus?.control,
        },
        focus_after: { role: focus.role, control: focus.control },
      },
    );
  });

  test(`hardening recovery ${recipe.operation} lost reply after the core accepted ${recipe.kind} reconciles read-only without replay`, async ({
    page,
  }, testInfo) => {
    let lose = false;
    const oracle = await openIntegratedShell(page, "smoke", {
      concurrent: concurrentFor(recipe),
      reply: () => {
        if (!lose) return "fulfill";
        lose = false;
        return "abort";
      },
    });
    const count = new Counter();
    const context = await recipe.prepare?.(page, count);
    const before = await shellSnapshot(page);
    const sent = oracle.transactions.length;
    const reads = oracle.reads();
    await page.evaluate(() => window.nleShellHarness.resetMeasurements());
    lose = true;
    await recipe.act(page, "pointer", context);
    const checks = new Checks();
    await checks.step("core_accepted_the_command", async () => {
      await expect.poll(() => oracle.transactions.length).toBe(sent + 1);
      expect(kinds(oracle.transactions.slice(sent))).toEqual([recipe.kind]);
      const history = oracle.lastHistory() as {
        rejection: unknown;
        snapshot: { timeline_revision: number };
      };
      expect(history.rejection).toBeNull();
      expect(history.snapshot.timeline_revision).toBe(
        before.timelineSnapshot!.timelineRevision + 1,
      );
    });
    await checks.step("one_read_only_reconciliation", async () => {
      await expect
        .poll(async () => (await shellSnapshot(page)).authoringStatus)
        .toBe("ready");
      expect(oracle.reads() - reads).toBe(1);
    });
    const after = await shellSnapshot(page);
    const accepted = oracle.lastHistory() as {
      snapshot: { timeline_revision: number; public_fingerprint: string };
    };
    await checks.step("adopted_the_accepted_state_without_a_receipt", () => {
      expect(after.receipts).toBe(before.receipts);
      expect(after.timelineSnapshot!.timelineRevision).toBe(
        accepted.snapshot.timeline_revision,
      );
      expect(after.timelineSnapshot!.publicFingerprint).toBe(
        accepted.snapshot.public_fingerprint,
      );
    });
    await checks.step("reported_unknown_never_rejected", () => {
      // This command's outcome is described from its own pending commit on; the rebase row
      // starts from a real refusal whose copy precedes it.
      const trace = after.commitStates;
      const from = trace.findIndex((state) => state.includes(PENDING_COPY));
      expect(from).toBeGreaterThanOrEqual(0);
      const outcome = trace.slice(from);
      expect(
        outcome.some((state) => state.includes("outcome is unknown")),
      ).toBe(true);
      expect(
        outcome.some(
          (state) =>
            REJECTED_COPY.some((copy) => state.includes(copy)) ||
            state.includes(CONFLICT_COPY),
        ),
      ).toBe(false);
    });
    await checks.step("accepted_revision_presented", async () => {
      await expect(page.locator(TIMELINE_STATUS)).toHaveAttribute(
        "data-h3-nle-timeline-revision",
        String(accepted.snapshot.timeline_revision),
      );
      await expect(page.locator(TIMELINE_STATUS)).toHaveAttribute(
        "data-h3-nle-save-state",
        "saved",
      );
      await expect(page.locator('[data-h3-nle-status="monitor"]')).toHaveText(
        "Monitor paused.",
      );
      await expect(page.locator('[data-h3-nle-status="trim"]')).toHaveAttribute(
        "data-h3-nle-trim-phase",
        "idle",
      );
    });
    const focus = await focusPlace(page);
    await checks.step("focus_stays_in_the_editor", () => {
      expect(focus).toMatchObject({
        connected: true,
        onBody: false,
        inEditor: true,
      });
    });
    await checks.step("nothing_replayed", () => {
      expect(oracle.transactions).toHaveLength(sent + 1);
    });
    await checks.step("next_command_uses_the_reconciled_base", async () => {
      // By keyboard: choose an unselected semantic clip. Re-activating the accepted selected clip
      // is intentionally a no-op under M25-46 and therefore cannot prove the reconciled CAS base.
      const freshSelection = page
        .locator(
          `${shellSurface} [data-h3-nle-control="selection.set"][aria-pressed="false"]`,
        )
        .first();
      await freshSelection.focus();
      await page.keyboard.press("Space");
      await expect
        .poll(async () => (await shellSnapshot(page)).receipts)
        .toBe(before.receipts + 1);
      const fresh = oracle.transactions.at(-1) as Kinded;
      expect(fresh.commands[0]!.kind).toBe("select_clips");
      expect(fresh.expected_timeline_revision).toBe(
        accepted.snapshot.timeline_revision,
      );
    });
    await hardeningEvidence(testInfo).row(
      `command.${recipe.kind}`,
      "recovery",
      checks,
      {
        injection: "response_loss",
        revision_before: before.timelineSnapshot!.timelineRevision,
        revision_reconciled: accepted.snapshot.timeline_revision,
        reconciliation_reads: 1,
        transactions: oracle.transactions.length - sent,
      },
    );
  });
}

test("integrated primary remove and Undo stay within the commit ceiling without a closed-preview reset", async ({
  page,
}, testInfo) => {
  const oracle = await openIntegratedShell(page, "smoke", { service: true });
  const count = new Counter();
  await select(page, "clip-0", count);
  const remove = recipes.find((recipe) => recipe.operation === "clip.remove")!;
  const base = await shellSnapshot(page);
  const baseFingerprint = base.timelineSnapshot!.timelineFingerprint;
  const sent = oracle.transactions.length;
  const measure = async (target: Locator, act: () => Promise<void>) => {
    // IMPORTANT: roving focus and its tooltip are navigation preparation, not accepted-edit cost;
    // settle the actual target before resetting the frozen per-edit commit counter.
    await target.focus();
    await expect(target).toBeFocused();
    let quiet = await shellSnapshot(page);
    let quietIntervals = 0;
    // IMPORTANT: an accepted edit can publish a delayed nested monitor update after one quiet
    // sample; require two consecutive quiet intervals or the next edit inherits that old cost.
    for (let interval = 0; interval < 20; interval += 1) {
      await page.waitForTimeout(250);
      const next = await shellSnapshot(page);
      if (next.nleCommits === quiet.nleCommits) {
        quietIntervals += 1;
        if (quietIntervals >= 2) break;
      } else quietIntervals = 0;
      quiet = next;
    }
    await page.evaluate(() => window.nleShellHarness.resetMeasurements());
    const railBefore = await page.locator(".h3-nle-trim-rail").count();
    await act();
    await settled(page, count);
    await expect(page.locator('[data-h3-nle-status="monitor"]')).toHaveText(
      "Monitor paused.",
    );
    const railAfter = await page.locator(".h3-nle-trim-rail").count();
    const geometry = await page.locator(".h3-nle-tracks").evaluate((grid) => {
      const canvas = grid.querySelector(".h3-nle-decoration");
      return {
        viewportHeight: grid.clientHeight,
        canvasHeight:
          canvas instanceof HTMLCanvasElement ? canvas.style.height : null,
        visibleRows: Number(grid.getAttribute("data-h3-nle-virtual-rows") ?? 0),
        totalRows: Number(grid.getAttribute("aria-rowcount") ?? 0),
      };
    });
    const expectedCanvasHeight = `${Math.min(geometry.viewportHeight, 8 * 56)}px`;
    await expect
      .poll(() =>
        page
          .locator(".h3-nle-tracks .h3-nle-decoration")
          .evaluate((canvas) => (canvas as HTMLElement).style.height),
      )
      .toBe(expectedCanvasHeight);
    return {
      snapshot: await shellSnapshot(page),
      railToggled: railBefore !== railAfter,
      geometry: { ...geometry, expectedCanvasHeight },
    };
  };

  const removeControl = page.locator('[data-h3-nle-control="clip.remove"]');
  const undoControl = page.locator('[data-h3-nle-control="history.undo"]');
  const removedEdit = await measure(removeControl, () =>
    remove.act(page, "pointer", undefined),
  );
  const restoredEdit = await measure(undoControl, () =>
    press(undoControl, page, "pointer"),
  );
  const removed = removedEdit.snapshot;
  const restored = restoredEdit.snapshot;
  const transactionKinds = kinds(oracle.transactions.slice(sent));
  const checks = new Checks();
  await checks.step("remove_and_undo_each_toggle_the_trim_rail", () => {
    expect(removedEdit.railToggled).toBe(true);
    expect(restoredEdit.railToggled).toBe(true);
  });
  await checks.step(
    "rail_reflow_keeps_virtual_rows_and_canvas_geometry_current",
    () => {
      for (const edit of [removedEdit, restoredEdit]) {
        expect(edit.geometry.canvasHeight).toBe(
          edit.geometry.expectedCanvasHeight,
        );
        expect(edit.geometry.visibleRows).toBeGreaterThanOrEqual(
          Math.min(
            edit.geometry.totalRows,
            Math.ceil(edit.geometry.viewportHeight / 56),
          ),
        );
      }
    },
  );
  await checks.step("the_primary_clip_is_removed_then_restored_by_undo", () => {
    expect(
      removed.timelineSnapshot!.clips.some((clip) => clip.clipId === "clip-0"),
    ).toBe(false);
    expect(
      restored.timelineSnapshot!.clips.some((clip) => clip.clipId === "clip-0"),
    ).toBe(true);
    expect(restored.timelineSnapshot!.timelineFingerprint).toBe(
      baseFingerprint,
    );
    expect(transactionKinds).toEqual(["remove_clip", "undo"]);
  });
  await checks.step(
    "each_accepted_edit_stays_within_four_overlay_commits",
    () => {
      for (const snapshot of [removed, restored]) {
        expect(snapshot.nleCommits).toBeGreaterThan(0);
        expect(
          snapshot.nleCommits,
          JSON.stringify(snapshot.commitStates),
        ).toBeLessThanOrEqual(4);
        expect(snapshot.commitStates).toHaveLength(snapshot.nleCommits);
      }
    },
  );
  await checks.step(
    "the_commit_trace_names_publication_viewport_and_monitor_state",
    () => {
      for (const snapshot of [removed, restored]) {
        for (const state of snapshot.commitStates) {
          expect(state).toMatch(/:rc\d+:sc\d+:/u);
          expect(state).toMatch(/:clips\d+:/u);
        }
        expect(snapshot.commitStates.at(-1)).toContain("Monitor paused.");
      }
    },
  );
  await hardeningEvidence(testInfo).row(
    "command.remove_undo_preview_invalidation",
    "stress",
    checks,
    {
      transition: "select primary -> remove -> Undo",
      transaction_kinds: transactionKinds,
      base_fingerprint: baseFingerprint,
      restored_fingerprint: restored.timelineSnapshot!.timelineFingerprint,
      remove_commits: removed.nleCommits,
      undo_commits: restored.nleCommits,
      remove_rail_toggled: removedEdit.railToggled,
      undo_rail_toggled: restoredEdit.railToggled,
      remove_geometry: removedEdit.geometry,
      undo_geometry: restoredEdit.geometry,
      remove_commit_states: removed.commitStates,
      undo_commit_states: restored.commitStates,
    },
  );
});

// The two `clip.trim` subcases the manifest names beside the command's own dimension rows: the
// edge grips as independent targets with a full keyboard draft/commit/cancel path, and every way
// an uncommitted draft must end without reaching the core.
const TRIM_PHASE = '[data-h3-nle-status="trim"]';
const GRIP = (edge: "start" | "end") =>
  `.h3-nle-trim-rail [data-h3-nle-trim-edge="${edge}"]:not([hidden])`;

type Box = { x: number; y: number; width: number; height: number };

/** The accepted clip geometry the core last answered with, for the selected clip. */
async function clipGeometry(page: Page, clipId: string) {
  const clip = (await shellSnapshot(page)).timelineSnapshot!.clips.find(
    (candidate) => candidate.clipId === clipId,
  )!;
  return { start: clip.startFrame, frames: clip.durationFrames };
}

test("hardening a11y clip.trim edge grips are separate 44px touch targets with keyboard draft, commit and cancel", async ({
  page,
}, testInfo) => {
  const oracle = await openIntegratedShell(page, "smoke", { service: true });
  const count = new Counter();
  await select(page, "clip-0", count);
  const checks = new Checks();
  const facts: Record<string, unknown> = {};
  const start = page.locator(`${shellSurface} ${GRIP("start")}`).first();
  const end = page.locator(`${shellSurface} ${GRIP("end")}`).first();
  await checks.step("each_edge_is_its_own_named_target", async () => {
    await expect(start).toHaveAccessibleName(/^Trim start of /);
    await expect(end).toHaveAccessibleName(/^Trim end of /);
    const boxes: Box[] = [
      (await start.boundingBox())!,
      (await end.boundingBox())!,
    ];
    facts.grips = boxes.map((box) => [
      Math.round(box.width),
      Math.round(box.height),
    ]);
    for (const box of boxes) {
      expect(box.width).toBeGreaterThanOrEqual(44);
      expect(box.height).toBeGreaterThanOrEqual(44);
    }
    // Separate targets: neither grip's centre lands inside the other's box.
    const centre = (box: Box) => ({
      x: box.x + box.width / 2,
      y: box.y + box.height / 2,
    });
    const inside = (box: Box, point: { x: number; y: number }) =>
      point.x >= box.x &&
      point.x <= box.x + box.width &&
      point.y >= box.y &&
      point.y <= box.y + box.height;
    expect(inside(boxes[0]!, centre(boxes[1]!))).toBe(false);
    expect(inside(boxes[1]!, centre(boxes[0]!))).toBe(false);
  });
  await checks.step("each_grip_is_hit_testable_and_focusable", async () => {
    for (const grip of [start, end]) {
      expect(
        await grip.evaluate((element) => {
          const rect = element.getBoundingClientRect();
          const top = document.elementFromPoint(
            rect.left + rect.width / 2,
            rect.top + rect.height / 2,
          );
          return top !== null && (top === element || element.contains(top));
        }),
      ).toBe(true);
      await grip.focus();
      await expect(grip).toBeFocused();
    }
  });
  await checks.step(
    "the_grip_describes_its_own_keyboard_contract",
    async () => {
      const described = await end.getAttribute("aria-describedby");
      expect(described).toBe("h3-nle-trim-instructions");
      await expect(page.locator(`#${described}`)).toContainText(
        "Arrow keys adjust the edge by one frame",
      );
    },
  );
  const before = await clipGeometry(page, "clip-0");
  const sent = oracle.transactions.length;
  await checks.step(
    "an_arrow_opens_a_draft_without_a_transaction",
    async () => {
      await end.focus();
      await page.keyboard.press("ArrowLeft");
      await expect(page.locator(TRIM_PHASE)).toHaveAttribute(
        "data-h3-nle-trim-phase",
        "keyboard_draft",
      );
      // M25-62 (R7): the grip is an icon; the rail label carries the live edge as a timecode.
      await expect(
        page.locator(`${shellSurface} .h3-nle-rail-label`),
      ).toContainText(timecode24(before.start + before.frames - 1));
      expect(oracle.transactions).toHaveLength(sent);
      expect(await clipGeometry(page, "clip-0")).toEqual(before);
    },
  );
  await checks.step(
    "escape_cancels_the_draft_and_changes_nothing",
    async () => {
      await page.keyboard.press("Escape");
      await expect(page.locator(TRIM_PHASE)).toHaveAttribute(
        "data-h3-nle-trim-phase",
        "idle",
      );
      expect(oracle.transactions).toHaveLength(sent);
      expect(await clipGeometry(page, "clip-0")).toEqual(before);
    },
  );
  await checks.step("enter_commits_exactly_one_trim", async () => {
    await end.focus();
    await page.keyboard.press("ArrowLeft");
    await page.keyboard.press("ArrowLeft");
    await page.keyboard.press("Enter");
    await settled(page, count);
    expect(oracle.transactions).toHaveLength(sent + 1);
    expect(kinds(oracle.transactions.slice(sent))).toEqual(["trim_clip"]);
    expect(await clipGeometry(page, "clip-0")).toEqual({
      start: before.start,
      frames: before.frames - 2,
    });
  });
  await checks.step("focus_stays_inside_the_editor", async () => {
    // The committed geometry replaces the grip, so the frozen requirement is the one the command
    // rows also assert -- a connected element inside the editor -- and where it landed is
    // recorded rather than prescribed.
    const focus = await focusPlace(page);
    expect(focus).toMatchObject({
      connected: true,
      onBody: false,
      inEditor: true,
    });
    facts.focus_after_commit = focus.control;
  });
  await hardeningEvidence(testInfo).row(
    "command.trim_clip",
    "edge_trim_accessible_input",
    checks,
    { ...facts, transactions: oracle.transactions.length - sent },
  );
  await oracle.close();
});

test("hardening recovery clip.trim drafts cancel on capture loss, Escape and a changed view without a transaction", async ({
  page,
}, testInfo) => {
  const oracle = await openIntegratedShell(page, "smoke", { service: true });
  const count = new Counter();
  await select(page, "clip-0", count);
  const checks = new Checks();
  const phase = page.locator(TRIM_PHASE);
  const end = page.locator(`${shellSurface} ${GRIP("end")}`).first();
  const before = await clipGeometry(page, "clip-0");
  const sent = oracle.transactions.length;
  const unchanged = async () => {
    await expect(phase).toHaveAttribute("data-h3-nle-trim-phase", "idle");
    expect(oracle.transactions).toHaveLength(sent);
    expect(await clipGeometry(page, "clip-0")).toEqual(before);
  };
  await checks.step("a_lost_pointer_capture_cancels_the_drag", async () => {
    const box = (await end.boundingBox())!;
    const x = box.x + box.width / 2;
    const y = box.y + box.height / 2;
    await page.mouse.move(x, y);
    await page.mouse.down();
    await page.mouse.move(x - 20, y, { steps: 4 });
    await expect(phase).toHaveAttribute("data-h3-nle-trim-phase", "dragging");
    // The real event the browser delivers when capture is taken away mid-gesture.
    await end.evaluate((element) =>
      element.dispatchEvent(
        new PointerEvent("lostpointercapture", { bubbles: true }),
      ),
    );
    await unchanged();
    await page.mouse.up();
    await unchanged();
  });
  await checks.step("escape_cancels_a_keyboard_draft", async () => {
    await end.focus();
    await page.keyboard.press("ArrowLeft");
    await expect(phase).toHaveAttribute(
      "data-h3-nle-trim-phase",
      "keyboard_draft",
    );
    await page.keyboard.press("Escape");
    await unchanged();
    // Escape on the grip never reaches the dialog: the editor is still open.
    await expect(page.locator(shellSurface)).toBeVisible();
  });
  await checks.step("leaving_the_grip_cancels_the_draft", async () => {
    await end.focus();
    await page.keyboard.press("ArrowLeft");
    await expect(phase).toHaveAttribute(
      "data-h3-nle-trim-phase",
      "keyboard_draft",
    );
    await page.keyboard.press("Tab");
    await unchanged();
  });
  await checks.step("a_changed_view_cancels_the_draft", async () => {
    await end.focus();
    await page.keyboard.press("ArrowLeft");
    await expect(phase).toHaveAttribute(
      "data-h3-nle-trim-phase",
      "keyboard_draft",
    );
    await page
      .locator(`${shellSurface} [data-h3-nle-control="transport.zoom_in"]`)
      .click();
    await unchanged();
  });
  await checks.step("the_grip_still_commits_afterwards", async () => {
    await end.focus();
    await page.keyboard.press("ArrowLeft");
    await page.keyboard.press("Enter");
    await settled(page, count);
    expect(kinds(oracle.transactions.slice(sent))).toEqual(["trim_clip"]);
    expect(await clipGeometry(page, "clip-0")).toEqual({
      start: before.start,
      frames: before.frames - 1,
    });
  });
  await hardeningEvidence(testInfo).row(
    "command.trim_clip",
    "edge_trim_cancel_conflict",
    checks,
    {
      cancellations: ["lostpointercapture", "escape", "focus_lost", "view"],
      transactions: oracle.transactions.length - sent,
    },
  );
  await oracle.close();
});
