// M25-16 expanded workspace copy. Every user-facing string of the launcher, overlay, workspace
// panes, inspector, sequence panel and import action lives here in the three shipped locales.
// The strings the item plan freezes are reproduced exactly.

import type { Locale } from "../../i18n/catalog";
import type { PrimaryAppendNotice } from "./nleCommandBuilders";

export const copy = {
  en: {
    launcher: "Open full editor",
    launcherBusy: "Opening full editor…",
    unsupported: "The full editor is unavailable in this browser.",
    heading: "Clip editor workspace",
    barTitle: "Clip editor",
    dialogName: "Clip editor workspace",
    close: "Close full editor",
    closeHint: "Escape closes the full editor",
    resize: "Resize workspace",
    resizeValue: "{width} by {height} pixels",
    surface: {
      opening: "Opening the full editor.",
      expanded: "Full editor ready.",
      closing: "Closing the full editor.",
      fallback:
        "Composition monitor unavailable; the preview shows the selected clip's source only.",
      monitorUnavailable: "Composition monitor unavailable.",
    },
    // M25-63 (R9): the top bar's save indicator. Short labels only; the full sentence is the
    // timeline status, and the revision number is never shown.
    save: {
      region: "Save status",
      loading: "Loading",
      saving: "Saving…",
      notSaved: "Not saved",
      checking: "Checking…",
      unknown: "Save status unknown",
      failed: "Edit failed",
      refused: "Edit refused",
      saved: "Saved",
      savedLive: "Saved.",
    },
    panes: {
      assets: "Media",
      text: "Text",
      sequence: "Sequence",
      inspector: "Inspector",
      switcher: "Media bin tabs",
      describe: {
        assets: "The media in this workspace.",
        text: "Add a title to the current timeline.",
        sequence:
          "Whole-video planning, generation and assembly for the Production project.",
      },
    },
    shell: {
      regions: {
        bin: "Media bin",
        monitor: "Preview monitor",
        inspector: "Inspector",
        timeline: "Timeline",
      },
      splitters: {
        bin_monitor: "Resize media bin and preview monitor",
        monitor_inspector: "Resize preview monitor and inspector",
        top_timeline: "Resize top panels and timeline",
      },
      splitterClickHint:
        "Click the left or top half to move the divider one step earlier; click the right or bottom half to move it one step later. Double-click resets it.",
      splitterValue: "{size} pixels",
      export: "Export",
      exportPanel: "Export final video",
    },
    summary: {
      title: "Clip editor project",
      counts: "{tracks} tracks, {clips} clips",
      duration: "Duration {timecode}",
      contentExtent: "Content extent {timecode}",
      editCapacity: "Edit capacity {timecode}",
      revision: "Accepted timeline revision {revision}",
      notLoaded:
        "Authoring workspace ready. Open the full editor to load its timeline.",
      absent: "No authoring workspace yet.",
      released: "The authoring workspace was released.",
      gone: "The authoring workspace expired.",
      loading: "Loading authoring workspace…",
      pending: "Applying command…",
      start: "Start authoring from this context",
      startUnavailable: "Create or open a Context workspace first.",
      refresh: "Refresh workspace",
      release: "Release workspace",
      confirmRelease: "Confirm release",
      keep: "Keep workspace",
      releaseWhileOpen: "Close the full editor to release the workspace.",
      actions: "Workspace actions",
      describe: {
        start:
          "Create the authoring workspace from the current context. Open the full editor to edit its timeline.",
        refresh: "Read the accepted workspace again. Nothing is changed.",
        release: "Release this workspace. The next step asks you to confirm.",
        confirmRelease:
          "Release the workspace now. Its timeline can no longer be edited.",
        keep: "Keep the workspace and cancel the release.",
      },
    },
    assets: {
      title: "Asset bin",
      empty: "No assets in this workspace.",
      noMatches: "No media matches these controls.",
      search: "Search media",
      sort: "Sort media",
      sortOriginal: "Source order",
      sortReverse: "Reverse order",
      filter: "Filter media",
      filterAll: "All media",
      filterVideo: "Videos",
      filterImage: "Pictures",
      filterAdded: "Added to timeline",
      sortFilter: "Sort and filter",
      view: "View",
      countLine: "{filter} · {count}",
      gridView: "Grid view",
      listView: "List view",
      card: "Clip {ordinal}",
      duration: "Duration {timecode}",
      durationUnavailable: "Duration unavailable",
      added: "Added to timeline",
      // M25-63: the pills over a thumbnail; the card's name keeps the full sentences.
      pillAdded: "Added",
      pillImported: "Imported",
      addToTimeline: "Add to timeline",
      // D-6: "+" states what Add does today (M25-59 makes it append to Main).
      addNamed: "Add {name} to the timeline",
      addTip: "Append to the end of the primary video track",
      addPrimaryMissing: "Add refused: the primary video track is unavailable.",
      addPrimaryLocked: "Add refused: unlock the primary video track first.",
      addTimingUnavailable:
        "Add refused: this asset has no usable timeline duration.",
      addInsufficientCapacity:
        "Add refused: the remaining timeline capacity is too short.",
      addRejected:
        "Add refused: the clip cannot be appended to the primary track.",
      addPending: "Adding clip to the end of the primary track…",
      addAccepted: "Clip added to the end of the primary track.",
      addStaleRevision:
        "Add refused because the timeline changed. Review the latest timeline and try again.",
      moreNamed: "More actions for {name}",
      moreActions: "More clip actions",
      insertAtPlayhead: "Insert at playhead",
      overwriteAtPlayhead: "Overwrite at playhead",
      thumbnailLoading: "Loading thumbnail",
      thumbnailUnavailable: "Thumbnail unavailable",
      textContent: "Title text",
      font: "Font {ordinal}",
      addTitle: "Add title",
      titleRefusals: {
        busy: "Wait for the current edit to finish.",
        missing_font: "Choose an available font before adding a title.",
        invalid_content:
          "Use 1–2,048 characters and at most 32 lines, without unsupported control characters.",
        unavailable_frame: "Choose a valid playhead position.",
        insufficient_capacity:
          "Set a positive editing duration before adding a title.",
        clip_limit: "The 128-clip limit has been reached. Remove a clip first.",
        track_limit:
          "All eight track slots are in use. Free a text track here or remove a track.",
      },
      kind: { video: "Video", image: "Picture", font: "Font" },
      frames: "{frames} source frames",
      embeddedAudio: {
        present_bound: "embedded audio",
        absent: "no embedded audio",
        unavailable: "embedded audio unavailable",
        excluded_overlay_policy: "embedded audio excluded on overlay",
      },
      imported: "Imported from Production",
      overlayAudioWarning:
        "Overlay video insertion excludes its embedded soundtrack.",
    },
    // M25-64 (row #28): the inspector's Project settings, read from the accepted output profile.
    project: {
      title: "Project",
      resolution: "Resolution",
      frameRate: "Frame rate",
      duration: "Duration",
      audio: "Audio",
      export: "Export format",
      size: "{width} × {height}",
      fps: "{fps} fps",
      kilohertz: "{rate} kHz",
      mono: "mono",
      stereo: "stereo",
      channels: "{count} channels",
      hint: "Select a clip or a track on the timeline to edit its properties.",
    },
    monitor: {
      title: "Monitor",
      // M25-64 (rows #26 and #27): the monitor's header and its two picture overlays.
      header: "Preview",
      emptyTitle: "Nothing on the timeline yet",
      unavailableTitle: "Preview unavailable",
      canvas: "Composition monitor",
      browserPreviewOnly:
        "Browser preview only. Render the final video for the exact output.",
      play: "Play",
      pause: "Pause",
      previousFrame: "Previous frame",
      nextFrame: "Next frame",
      seek: "Transport position",
      seekValue: "Frame {frame} of {last}",
      frameUnavailable: "Frame unavailable",
      recover: "Retry",
      transform: {
        move: "Move selected clip",
        north_west: "Scale selected clip from top left",
        north: "Scale selected clip from top",
        north_east: "Scale selected clip from top right",
        east: "Scale selected clip from right",
        south_east: "Scale selected clip from bottom right",
        south: "Scale selected clip from bottom",
        south_west: "Scale selected clip from bottom left",
        west: "Scale selected clip from left",
        rotate: "Rotate selected clip",
      },
      transport: {
        label: "Monitor transport",
        viewLabel: "Monitor view",
        playDescription: "Play the composition from the current frame.",
        pauseDescription: "Pause playback on the current frame.",
        previousFrameDescription: "Step back one frame.",
        nextFrameDescription: "Step forward one frame.",
        fit: "Fit picture",
        fitDescription: "Fit the whole picture inside the monitor.",
        actual: "Actual size",
        actualDescription: "Show one composition pixel per screen pixel.",
        view: { fit: "Fit", actual: "100%" },
        fullscreen: "Full screen",
        fullscreenDescription:
          "Show the monitor on the whole screen. Escape leaves full screen.",
        fullscreenExit: "Leave full screen",
        fullscreenExitDescription: "Return the monitor to the workspace.",
        fullscreenUnavailable: "Full screen is unavailable in this browser.",
        fullscreenRefused: "Full screen was refused.",
        timecode: "{current} / {total}",
        timecodeLabel: "Timecode {current} of {total}",
      },
      status: {
        closed: "Monitor closed.",
        opening: "Opening monitor.",
        paused: "Monitor paused.",
        playing: "Monitor playing.",
        closing: "Closing monitor.",
        blocked: "Monitor unavailable: {reason}.",
        cleanup_pending: "Monitor cleanup is pending.",
      },
      blocker: {
        source_unavailable: "source unavailable",
        canvas_unavailable: "canvas unavailable",
        invalid_contract: "unsupported composition",
        resource_limit: "resource limit exceeded",
      },
      // M25-64 (A64-6): the unavailable overlay's reason, a plain sentence under its title. The
      // status sentence above stays the diagnostics text.
      unavailableReason: {
        source_unavailable: "A clip's source could not be read.",
        canvas_unavailable: "The browser could not draw the picture.",
        invalid_contract: "This composition can't be previewed.",
        resource_limit:
          "The preview needs more resources than the browser allows.",
        cleanup_pending: "The previous preview is still closing.",
      },
      selectedSourceOnly: "Selected source only",
      selectedSourceNone: "Select a clip with a source to preview it.",
      emptyHint:
        "Press + on a thumbnail in Media, or drag it to the timeline, to preview it here.",
    },
    audio: {
      title: "Embedded audio",
      policy:
        "Embedded source audio follows primary video edits. A clip's volume, mute and fades are set in its Audio tab; separate audio tracks are unavailable in this release.",
      state: {
        silent: "Silent",
        following: "Following primary video",
        seeking: "Seeking",
        suspended: "Suspended",
        unavailable: "Unavailable",
      },
      owner: "Owner clip {clip}",
      noOwner: "No owner clip",
    },
    timeline: {
      title: "Timeline",
      menus: {
        trackMenu: "Track menu",
        clipMenu: "Clip menu",
        openTrack: "Open track menu",
        openClip: "Open clip menu",
        trimStartEarlier: "Trim start earlier by one frame",
        trimStartLater: "Trim start later by one frame",
        trimEndEarlier: "Trim end earlier by one frame",
        trimEndLater: "Trim end later by one frame",
      },
      grid: "Timeline tracks",
      trackNames: { main: "Main", overlay: "Overlay {n}", text: "Text {n}" },
      trackToggles: { lock: "Lock {name}", show: "Show {name}" },
      trackKind: {
        primary_video: "Primary video",
        video_overlay: "Video overlay",
        image_overlay: "Picture overlay",
        text_overlay: "Text overlay",
      },
      trackActions: {
        lock: "Lock track",
        unlock: "Unlock track",
        enable: "Show track",
        disable: "Hide track",
      },
      toolbar: {
        label: "Timeline tools",
        more: "More timeline tools",
        withShortcut: "{text} ({keys})",
        labels: {
          undo: "Undo",
          redo: "Redo",
          split: "Split at playhead",
          trimStart: "Trim start to playhead",
          trimEnd: "Trim end to playhead",
          delete: "Delete",
          rippleDelete: "Ripple delete",
          snap: "Snapping",
          ripple: "Main-track ripple",
          zoomOut: "Zoom out",
          zoomIn: "Zoom in",
          fit: "Fit timeline",
          rebase: "Rebase rejected edit",
        },
        descriptions: {
          undo: "Undo the last accepted timeline edit.",
          redo: "Redo the next accepted timeline edit.",
          split: "Split the selected clip at the current playhead.",
          trimStart: "Move the selected clip's start to the current playhead.",
          trimEnd: "Move the selected clip's end to the current playhead.",
          delete: "Delete the selected clips in one edit.",
          rippleDelete:
            "Delete one clip and shift following clips on its track.",
          snap: "Snap timeline edits to nearby boundaries.",
          ripple:
            "Shift following clips on the edited track during trim or delete.",
          zoomOut: "Show more of the timeline.",
          zoomIn: "Show less of the timeline with more detail.",
          fit: "Fit the whole timeline in the lane.",
          rebase:
            "Reapply the exact rejected attribute edit to the accepted timeline.",
          more: "Open lower-priority timeline view and selection tools.",
        },
        unavailable: {
          busy: "Another timeline operation is in progress.",
          selection_required: "Select at least one clip.",
          single_selection_required: "Select exactly one clip.",
          stale_selection:
            "The selection no longer exists in the accepted timeline.",
          locked_track: "A selected clip is on a locked track.",
          playhead_unavailable: "The playhead is unavailable.",
          playhead_outside_clip:
            "Place the playhead strictly inside the selected clip.",
          clip_capacity: "The timeline already contains 128 clips.",
          command_limit: "Select no more than 32 clips for one edit.",
          history_unavailable: "No redo history is available.",
          rebase_unavailable:
            "No eligible rejected attribute edit is available.",
          cut_unavailable: "The selected cut is no longer adjacent.",
          source_range_unavailable:
            "This edit point does not match an admitted source frame.",
          empty_roll_side:
            "A roll must leave at least one frame on both sides.",
        },
      },
      clip: "{name}, {start}–{end}, {duration}",
      titleClip: "Title",
      railLabel: "{name} · {start}–{end}",
      emptyLane: "Drag media here, or press + on a thumbnail",
      selected: "selected",
      trimStart: "Trim start of {name}",
      snap: "Snap edges",
      trimEnd: "Trim end of {name}",
      trimDraft: "{edge} edge {delta} frames",
      trimInstructions:
        "Arrow keys adjust the edge by one frame; Shift+Arrow by one grid step; Enter commits; Escape cancels.",
      trimSubmitting: "Committing trim…",
      trimRejected: "Trim not applied; the current timeline is shown.",
      trimAccepted: "Trim accepted.",
      trimReconciling:
        "Trim response lost; reconciling with the accepted timeline.",
      edgeStart: "Start",
      edgeEnd: "End",
      zoomIn: "Zoom in",
      zoomOut: "Zoom out",
      zoomFit: "Fit timeline",
      zoomSelection: "Zoom to selection",
      previousClip: "Previous clip",
      nextClip: "Next clip",
      additiveSelection: "Add to selection",
      rangeSelection: "Extend selection range",
      clearSelection: "Clear selection",
      selectAll: "Select all clips",
      move: "Move clip or group",
      moveEarlier: "Move earlier by one grid step",
      moveLater: "Move later by one grid step",
      moveTrackUp: "Move to the previous track",
      moveTrackDown: "Move to the next track",
      apply: "Apply",
      cancel: "Cancel",
      seekPreviousFrame: "Seek one frame earlier",
      seekNextFrame: "Seek one frame later",
      panEarlier: "Pan timeline earlier",
      panLater: "Pan timeline later",
      moveDraft: "Move draft: {delta} frames",
      insertDraft: "Insert at frame {frame}",
      insertRefused: "Can't insert. {reason}",
      insertSubmitting: "Inserting clip…",
      insertAccepted: "Clip inserted.",
      insertRejected: "Clip not inserted; the accepted timeline is shown.",
      insertReconciling:
        "Insert response lost; reconciling the accepted timeline.",
      moveSubmitting: "Committing move…",
      moveAccepted: "Move accepted.",
      moveRejected: "Move not applied; the accepted timeline is shown.",
      moveReconciling: "Move response lost; reconciling the accepted timeline.",
      // B-M2562-06: a refusal names its cause in words; the reason code stays in `data-code`.
      moveRefused: "Can't move. {reason}",
      moveRefusals: {
        group_limit: "Move 32 clips or fewer at a time.",
        locked_track: "The track is locked.",
        overlap: "It would overlap another clip.",
        bounds: "It would pass the start or end of the timeline.",
        incompatible_track: "That track can't hold this clip.",
        primary_track: "Main takes only video clips already on it.",
        source_missing: "The clip's track is missing.",
        target_exhaustion: "There's no track to move to.",
        other: "This move isn't possible here.",
      },
      zoomStatus: "Zoom {zoom}x",
      zoomContinuous: "Timeline zoom",
      scroll: "Timeline view start",
      playhead: "Playhead",
      playheadValue: "Frame {frame}",
      virtualized: "Showing tracks {first} to {last} of {total}",
      empty: "The timeline has no clips.",
      loading: "Loading timeline…",
      absent:
        "No authoring workspace. Start one from this context, or import generated clips from Production.",
      revision: "Accepted timeline revision {revision}",
      receipt: "Last edit saved.",
      outcomeUnknownReading:
        "The command's outcome is unknown; re-reading the current timeline. Nothing was replayed.",
      outcomeUnknownReadFailed:
        "The command's outcome is unknown and the timeline could not be re-read. Nothing was replayed.",
      conflict:
        "The workspace changed or the command was rejected; the accepted backend state is shown.",
      pending: "Applying command…",
    },
    inspector: {
      title: "Inspector",
      noSelection: "Select a clip or track to edit it.",
      draftDiscarded:
        "An unsent edit in this section was cleared because the timeline changed.",
      selection: "Selection: {count} clips",
      trackSection: "Track",
      clipSection: "Clip",
      rangeSection: "Range",
      historySection: "History",
      apply: "Apply",
      clipId: "Clip",
      trackId: "Track",
      assetId: "Asset",
      newId: "New identifier",
      kind: "Kind",
      order: "Order",
      enabled: "Enabled",
      locked: "Locked",
      startFrame: "Start frame",
      durationFrames: "Duration frames",
      sourceStartFrame: "Source start frame",
      deltaFrames: "Delta frames",
      edge: "Edge",
      offsetFrames: "Offset frames",
      leftClip: "Left clip",
      rightClip: "Right clip",
      scopeTracks: "Scope tracks",
      opacity: "Opacity",
      blend: "Blend",
      blendModes: { normal: "Normal", multiply: "Multiply", screen: "Screen" },
      transitionKind: "Transition",
      transitionKinds: { none: "None", cross_dissolve_v1: "Cross dissolve" },
      transitionFrames: "Transition frames",
      effectKind: "Effect",
      effectKinds: { none: "None", color_adjust_v1: "Color adjustment" },
      brightness: "Brightness",
      contrast: "Contrast",
      saturation: "Saturation",
      positionX: "Position X",
      positionY: "Position Y",
      scaleX: "Scale X",
      scaleY: "Scale Y",
      rotation: "Rotation",
      anchorX: "Anchor X",
      anchorY: "Anchor Y",
      cropLeft: "Crop left",
      cropTop: "Crop top",
      cropRight: "Crop right",
      cropBottom: "Crop bottom",
      // M25-64 (R10): a unit field's accessible name; the visible label carries no unit token.
      unitName: "{label} ({unit})",
      // M25-64 (row #29): the clip header's range line.
      clipRange: "{start} – {end} · {duration}",
      seconds: "{seconds} s",
      textContent: "Text",
      fontAsset: "Font asset",
      fontSize: "Size (px)",
      fontWeight: "Weight",
      fontWeights: { regular: "Regular", bold: "Bold" },
      textColor: "Color",
      // A video clip's own audio: its gain, mute and fades.
      volume: "Volume",
      mute: "Mute",
      fadeIn: "Fade in",
      fadeOut: "Fade out",
      operations: {
        create_track: "Add track",
        remove_track: "Remove track",
        reorder_track: "Reorder track",
        set_track_enabled: "Track enabled",
        set_track_locked: "Track locked",
        insert_asset_clip: "Insert asset clip",
        insert_title_clip: "Insert title clip",
        replace_clip_asset: "Replace clip asset",
        remove_clip: "Remove clip",
        move_clip: "Move clip",
        move_group: "Move selected group",
        trim_clip: "Trim clip",
        split_clip: "Split clip",
        merge_clips: "Merge clips",
        insert_range: "Insert range",
        overwrite_range: "Overwrite range",
        ripple_delete: "Ripple delete",
        ripple_trim: "Ripple trim",
        roll_edit: "Roll edit",
        slip_clip: "Slip clip",
        slide_clip: "Slide clip",
        set_clip_enabled: "Clip enabled",
        set_visual_transform: "Transform",
        set_crop: "Crop",
        set_opacity_blend: "Opacity and blend",
        set_text_content: "Text content",
        set_text_style: "Text style",
        set_transition: "Transition",
        set_effect: "Effect",
        set_clip_audio: "Clip audio",
        select_clips: "Select clips",
        undo: "Undo",
        redo: "Redo",
        rebase_transaction: "Rebase pending edit",
      },
      rebaseHint:
        "Re-applies the last rejected attribute edit onto the current accepted timeline.",
      rebaseUnavailable: "No rebasable edit is pending.",
    },
    render: {
      title: "Render",
      unavailable: "Final render unavailable on this host.",
      stale: "Timeline changed; refresh the workspace before rendering.",
    },
    sequence: {
      title: "Whole-video sequence",
      planningLocation:
        "Plan the video in Production. Closing the editor returns you there.",
      target: "Target duration (seconds)",
      policy: "Segmentation policy",
      policies: {
        auto_storyboard: "Automatic storyboard",
        fixed_5: "Fixed 5 s",
        fixed_10: "Fixed 10 s",
        fixed_12: "Fixed 12 s",
        fixed_15: "Fixed 15 s",
      },
      prepare: "Prepare planning context",
      prepared: "Planning context prepared (revision {revision}).",
      sourceAndTarget:
        "Source context: {source} s. Production target: {target} s.",
      segmentDurations: "Requested and sampled segment durations",
      segmentDuration:
        "Segment {ordinal}: requested {requested} s; sampled {delivered} s ({frames} frames).",
      admitCanonical: "Use generated storyboard",
      reviewStoryboard: "Review storyboard rows",
      admitReviewed: "Use reviewed rows",
      addRow: "Add shot",
      removeRow: "Remove shot {ordinal}",
      shotText: "Shot {ordinal} text",
      shotStart: "Start (ms)",
      shotEnd: "End (ms)",
      hardBoundary: "Hard boundary",
      propose: "Propose segments",
      proposal: "Proposed plan: {count} segments",
      proposalSegment: "{ordinal}. {mode} {seconds} s",
      blockers: "Cannot import yet",
      holds: "Before generating",
      approveImport: "Approve and import to Production",
      createPlannedProject: "Create planned project",
      planningActions: "Sequence planning actions",
      reviewActions: "Storyboard row actions",
      scriptLabel: "Storyboard script",
      scriptHint:
        "Write the whole video as shots: start each with [Shot 1], [Shot 2] and so on, or separate shots with a blank line. To set the cuts yourself, give every shot after the first a start such as “[Shot 2] At 00:08,”. Otherwise the shots share the target duration evenly.",
      scriptActions: "Storyboard script actions",
      scriptLoadContext: "Load shots from Context",
      scriptSplit: "Split script into shots",
      scriptSplitTimed: "{count} shots, cut at the times in the script.",
      scriptSplitEven: "{count} shots, spaced evenly across {target} s.",
      scriptErrors: {
        script_empty: "Write the shots of the video first.",
        script_shape:
          "The shots could not be read. Start with [Shot 1] and number the shots in order, each with its own text.",
        script_mixed_timing:
          "Give every shot after the first a start time, or none of them.",
        script_time_range:
          "Shot start times must increase and fall inside the target duration.",
        script_too_many_shots:
          "Too many shots for this target. Use fewer shots or a longer target duration.",
        script_shot_too_long: "A shot's text is too long. Shorten it.",
        script_too_long: "The script is too long. Shorten it.",
        script_context_empty:
          "The Context prompt has no shot list to load. Write the shots here.",
      },
      readinessActions: "Readiness",
      describe: {
        prepare:
          "Reads the current Context and Production project and binds the target duration and segmentation policy to them.",
        admitCanonical:
          "Uses the storyboard written into the optimized prompt as this plan's shot list. It applies when the target duration is the length of that one clip.",
        scriptLoadContext:
          "Copies the shots the Context prompt describes into the script box, without their clip times, so you can extend them across the whole video.",
        scriptSplit:
          "Replaces the shot rows below with the script's shots, timed across the target duration. Nothing is used until you choose to use the reviewed rows.",
        reviewStoryboard:
          "Shows the shot rows so you can edit their text, timing and hard boundaries before using them.",
        propose:
          "Splits the storyboard into Production segments with durations and modes for you to review.",
        approveImport:
          "Creates the proposed segments in the Production project. Nothing is queued for generation.",
        readiness:
          "Checks whether the imported plan can be generated with the current host, models and extension.",
        addRow: "Adds a five-second shot after the last row.",
        admitReviewed: "Uses your edited shot rows as this plan's storyboard.",
        createPlannedProject:
          "Starts a new Production project from the current Context so this plan can be imported into it.",
      },
      imported: "Plan imported: {count} segments",
      stale:
        "The Production workspace changed; prepare the planning context again.",
      readiness: "Check readiness",
      readinessState: {
        idle: "Readiness not checked",
        requesting: "Checking readiness…",
        held: "Not ready to generate",
        ready: "Ready to generate",
        error: "Readiness check unavailable",
      },
      start: "Generate approved sequence",
      detach: "Continue current segment while I leave",
      detachHint:
        "Only the current segment may finish. Remaining segments will pause until you return and choose Resume.",
      recoveryDeadline:
        "Recovery is available until {deadline}. Returning does not extend this deadline.",
      resume: "Resume remaining segments",
      reattach: "Reconnect to running sequence",
      cancel: "Cancel sequence",
      retrySegment: "Retry segment {ordinal}",
      refresh: "Refresh sequence",
      state: {
        idle: "No sequence running",
        starting: "Starting sequence…",
        attached_current_child: "Running current segment",
        detach_ready: "Current segment queued; you may leave",
        detaching: "Detaching…",
        safe_to_leave: "Safe to leave",
        reattach_reconciling: "Reconnecting…",
        current_segment_completed:
          "Current segment completed; later segments paused",
        current_segment_still_owned:
          "Host may still be working; later segments paused",
        paused_unknown_ownership:
          "Segment status unknown; later segments paused",
        resume_ready: "Ready to resume",
        recovery_unavailable_or_expired: "Reconnection unavailable",
        finished: "Sequence finished",
        failed: "Sequence paused on failure",
      },
      slot: "{ordinal}. {state}",
      recoveryPointer: "A previous sequence can be reconnected.",
      assembly: "Assembly",
      assemble: "Assemble sequence",
      cancelAssembly: "Cancel assembly",
      retryAssembly: "Retry assembly",
      assemblyState: "{state} ({completed} of {total})",
      assemblyProfile:
        "Assembly normalizes output to 30 fps, 48 kHz stereo. Source context duration remains separate.",
      assemblyInputs: "Built from {artifacts} segment videos and {cuts} cuts.",
      assemblyReceipt: "Assembly completed and verified.",
      productionUnavailable: "Production workspace unavailable.",
      contextUnavailable: "Context workspace unavailable.",
    },
  },
  "zh-TW": {
    launcher: "開啟完整剪輯器",
    launcherBusy: "正在開啟完整剪輯器…",
    unsupported: "此瀏覽器無法使用完整剪輯器。",
    heading: "剪輯器工作區",
    barTitle: "剪輯器",
    dialogName: "剪輯器工作區",
    close: "關閉完整剪輯器",
    closeHint: "按 Escape 關閉完整剪輯器",
    resize: "調整工作區大小",
    resizeValue: "{width} × {height} 像素",
    surface: {
      opening: "正在開啟完整剪輯器。",
      expanded: "完整剪輯器已就緒。",
      closing: "正在關閉完整剪輯器。",
      fallback: "合成監視器無法使用；預覽僅顯示所選片段的來源。",
      monitorUnavailable: "合成監視器無法使用。",
    },
    save: {
      region: "儲存狀態",
      loading: "載入中",
      saving: "正在儲存…",
      notSaved: "未儲存",
      checking: "正在確認…",
      unknown: "儲存狀態不明",
      failed: "編輯失敗",
      refused: "編輯遭拒",
      saved: "已儲存",
      savedLive: "已儲存。",
    },
    panes: {
      assets: "素材",
      text: "文字",
      sequence: "序列",
      inspector: "檢視器",
      switcher: "素材區分頁",
      describe: {
        assets: "此工作區內的素材。",
        text: "在目前的時間軸加入標題。",
        sequence: "為 Production 專案規劃、生成與組裝整部影片。",
      },
    },
    shell: {
      regions: {
        bin: "素材區",
        monitor: "預覽監視器",
        inspector: "檢視器",
        timeline: "時間軸",
      },
      splitters: {
        bin_monitor: "調整素材區與預覽監視器大小",
        monitor_inspector: "調整預覽監視器與檢視器大小",
        top_timeline: "調整上方面板與時間軸大小",
      },
      splitterClickHint:
        "點擊分隔線左側或上側可向前移動一格；點擊右側或下側可向後移動一格。雙擊可重設。",
      splitterValue: "{size} 像素",
      export: "匯出",
      exportPanel: "匯出最終影片",
    },
    summary: {
      title: "剪輯器專案",
      counts: "{tracks} 條軌道、{clips} 個片段",
      duration: "長度 {timecode}",
      contentExtent: "內容範圍 {timecode}",
      editCapacity: "編輯容量 {timecode}",
      revision: "已接受的時間軸修訂 {revision}",
      notLoaded: "創作工作區已就緒。開啟完整剪輯器以載入時間軸。",
      absent: "尚無創作工作區。",
      released: "創作工作區已釋放。",
      gone: "創作工作區已過期。",
      loading: "正在載入創作工作區…",
      pending: "正在套用指令…",
      start: "從此脈絡開始創作",
      startUnavailable: "請先建立或開啟 Context 工作區。",
      refresh: "重新整理工作區",
      release: "釋放工作區",
      confirmRelease: "確認釋放",
      keep: "保留工作區",
      releaseWhileOpen: "關閉完整剪輯器後才能釋放工作區。",
      actions: "工作區操作",
      describe: {
        start: "從目前的脈絡建立創作工作區。開啟完整剪輯器以編輯其時間軸。",
        refresh: "重新讀取已接受的工作區，不會變更任何內容。",
        release: "釋放此工作區。下一步會請你確認。",
        confirmRelease: "立即釋放工作區。之後無法再編輯其時間軸。",
        keep: "保留工作區並取消釋放。",
      },
    },
    assets: {
      title: "素材箱",
      empty: "此工作區沒有素材。",
      noMatches: "沒有符合條件的素材。",
      search: "搜尋素材",
      sort: "排序素材",
      sortOriginal: "來源順序",
      sortReverse: "反向順序",
      filter: "篩選素材",
      filterAll: "所有素材",
      filterVideo: "影片",
      filterImage: "圖片",
      filterAdded: "已加入時間軸",
      sortFilter: "排序與篩選",
      view: "檢視",
      countLine: "{filter} · {count}",
      gridView: "格狀檢視",
      listView: "清單檢視",
      card: "片段 {ordinal}",
      duration: "長度 {timecode}",
      durationUnavailable: "長度無法使用",
      added: "已加入時間軸",
      pillAdded: "已加入",
      pillImported: "已匯入",
      addToTimeline: "加入時間軸",
      addNamed: "將 {name} 加入時間軸",
      addTip: "附加到主要視訊軌末端",
      addPrimaryMissing: "無法加入：主要視訊軌不可用。",
      addPrimaryLocked: "無法加入：請先解除主要視訊軌鎖定。",
      addTimingUnavailable: "無法加入：此素材沒有可用的時間軸長度。",
      addInsufficientCapacity: "無法加入：時間軸剩餘容量不足。",
      addRejected: "無法加入：片段無法附加到主要視訊軌。",
      addPending: "正在將片段加入主要視訊軌末端…",
      addAccepted: "片段已加入主要視訊軌末端。",
      addStaleRevision: "無法加入：時間軸已變更，請確認最新內容後重試。",
      moreNamed: "{name} 的更多動作",
      moreActions: "更多片段操作",
      insertAtPlayhead: "在播放位置插入",
      overwriteAtPlayhead: "在播放位置覆寫",
      thumbnailLoading: "正在載入縮圖",
      thumbnailUnavailable: "縮圖無法使用",
      textContent: "標題文字",
      font: "字型 {ordinal}",
      addTitle: "加入標題",
      titleRefusals: {
        busy: "請等目前的編輯完成。",
        missing_font: "請先選擇可用字型，再加入標題。",
        invalid_content:
          "請使用 1–2,048 個字元、最多 32 行，且不要包含不支援的控制字元。",
        unavailable_frame: "請選擇有效的播放位置。",
        insufficient_capacity: "請先設定大於零的編輯長度，再加入標題。",
        clip_limit: "已達 128 個片段的上限，請先移除一個片段。",
        track_limit:
          "八個軌道位置都已使用，請空出此位置的文字軌或移除一個軌道。",
      },
      kind: { video: "影片", image: "圖片", font: "字型" },
      frames: "{frames} 個來源影格",
      embeddedAudio: {
        present_bound: "內嵌音訊",
        absent: "無內嵌音訊",
        unavailable: "內嵌音訊無法使用",
        excluded_overlay_policy: "疊加層排除內嵌音訊",
      },
      imported: "從製作匯入",
      overlayAudioWarning: "插入疊加影片會排除其內嵌音軌。",
    },
    project: {
      title: "專案",
      resolution: "解析度",
      frameRate: "影格速率",
      duration: "長度",
      audio: "音訊",
      export: "匯出格式",
      size: "{width} × {height}",
      fps: "{fps} fps",
      kilohertz: "{rate} kHz",
      mono: "單聲道",
      stereo: "立體聲",
      channels: "{count} 聲道",
      hint: "選取時間軸上的片段或軌道，即可編輯其屬性。",
    },
    monitor: {
      title: "監視器",
      header: "預覽",
      emptyTitle: "時間軸上還沒有內容",
      unavailableTitle: "預覽無法使用",
      canvas: "合成監視器",
      browserPreviewOnly: "僅為瀏覽器預覽；精確輸出請轉譯最終影片。",
      play: "播放",
      pause: "暫停",
      previousFrame: "上一影格",
      nextFrame: "下一影格",
      seek: "播放位置",
      seekValue: "第 {frame} 影格，共 {last}",
      frameUnavailable: "影格無法使用",
      recover: "重試",
      transform: {
        move: "移動所選片段",
        north_west: "從左上縮放所選片段",
        north: "從上方縮放所選片段",
        north_east: "從右上縮放所選片段",
        east: "從右側縮放所選片段",
        south_east: "從右下縮放所選片段",
        south: "從下方縮放所選片段",
        south_west: "從左下縮放所選片段",
        west: "從左側縮放所選片段",
        rotate: "旋轉所選片段",
      },
      transport: {
        label: "監視器播放控制",
        viewLabel: "監視器檢視",
        playDescription: "從目前影格播放合成內容。",
        pauseDescription: "在目前影格暫停播放。",
        previousFrameDescription: "後退一個影格。",
        nextFrameDescription: "前進一個影格。",
        fit: "符合視窗",
        fitDescription: "將整個畫面縮放到監視器內。",
        actual: "原始大小",
        actualDescription: "以一個合成像素對一個螢幕像素顯示。",
        view: { fit: "符合視窗", actual: "100%" },
        fullscreen: "全螢幕",
        fullscreenDescription: "以全螢幕顯示監視器；按 Escape 離開全螢幕。",
        fullscreenExit: "離開全螢幕",
        fullscreenExitDescription: "將監視器返回工作區。",
        fullscreenUnavailable: "此瀏覽器無法使用全螢幕。",
        fullscreenRefused: "全螢幕要求遭拒。",
        timecode: "{current} / {total}",
        timecodeLabel: "時間碼 {current}，共 {total}",
      },
      status: {
        closed: "監視器已關閉。",
        opening: "正在開啟監視器。",
        paused: "監視器已暫停。",
        playing: "監視器播放中。",
        closing: "正在關閉監視器。",
        blocked: "監視器無法使用：{reason}。",
        cleanup_pending: "監視器清理尚未完成。",
      },
      blocker: {
        source_unavailable: "來源無法使用",
        canvas_unavailable: "畫布無法使用",
        invalid_contract: "不支援的合成內容",
        resource_limit: "超出資源上限",
      },
      unavailableReason: {
        source_unavailable: "無法讀取片段的來源。",
        canvas_unavailable: "瀏覽器無法繪製畫面。",
        invalid_contract: "此合成內容無法預覽。",
        resource_limit: "預覽所需資源超出瀏覽器上限。",
        cleanup_pending: "先前的預覽仍在關閉中。",
      },
      selectedSourceOnly: "僅顯示所選來源",
      selectedSourceNone: "選取含來源的片段以預覽。",
      emptyHint:
        "按「媒體」中縮圖上的「+」，或將它拖曳到時間軸，即可在此預覽。",
    },
    audio: {
      title: "內嵌音訊",
      policy:
        "內嵌來源音訊會跟隨主要影片的編輯。片段的音量、靜音與淡入淡出可在其「音訊」分頁設定；本版本不提供獨立音軌。",
      state: {
        silent: "靜音",
        following: "跟隨主要影片",
        seeking: "搜尋中",
        suspended: "已暫停",
        unavailable: "無法使用",
      },
      owner: "擁有片段 {clip}",
      noOwner: "沒有擁有片段",
    },
    timeline: {
      title: "時間軸",
      menus: {
        trackMenu: "軌道選單",
        clipMenu: "片段選單",
        openTrack: "開啟軌道選單",
        openClip: "開啟片段選單",
        trimStartEarlier: "起點提前一格",
        trimStartLater: "起點延後一格",
        trimEndEarlier: "終點提前一格",
        trimEndLater: "終點延後一格",
      },
      grid: "時間軸軌道",
      trackNames: { main: "主軌", overlay: "疊加 {n}", text: "文字 {n}" },
      trackToggles: { lock: "鎖定 {name}", show: "顯示 {name}" },
      trackKind: {
        primary_video: "主要影片",
        video_overlay: "疊加影片",
        image_overlay: "疊加圖片",
        text_overlay: "疊加文字",
      },
      trackActions: {
        lock: "鎖定軌道",
        unlock: "解除鎖定軌道",
        enable: "顯示軌道",
        disable: "隱藏軌道",
      },
      toolbar: {
        label: "時間軸工具",
        more: "更多時間軸工具",
        withShortcut: "{text}（{keys}）",
        labels: {
          undo: "復原",
          redo: "重做",
          split: "在播放頭分割",
          trimStart: "將起點修剪到播放頭",
          trimEnd: "將終點修剪到播放頭",
          delete: "刪除",
          rippleDelete: "漣漪刪除",
          snap: "吸附",
          ripple: "主軌漣漪",
          zoomOut: "縮小",
          zoomIn: "放大",
          fit: "符合時間軸",
          rebase: "重新套用遭拒編輯",
        },
        descriptions: {
          undo: "復原最後一次已接受的時間軸編輯。",
          redo: "重做下一次已接受的時間軸編輯。",
          split: "在目前播放頭分割所選片段。",
          trimStart: "將所選片段的起點移到目前播放頭。",
          trimEnd: "將所選片段的終點移到目前播放頭。",
          delete: "在一次編輯中刪除所選片段。",
          rippleDelete: "刪除一個片段並移動其軌道後續片段。",
          snap: "將時間軸編輯吸附到鄰近邊界。",
          ripple: "修剪或刪除時移動同軌後續片段。",
          zoomOut: "顯示更多時間軸。",
          zoomIn: "放大以顯示更多細節。",
          fit: "讓整個時間軸符合軌道寬度。",
          rebase: "將完全相同的遭拒屬性編輯重新套用到已接受時間軸。",
          more: "開啟較低優先序的時間軸檢視與選取工具。",
        },
        unavailable: {
          busy: "另一項時間軸操作正在進行。",
          selection_required: "請至少選取一個片段。",
          single_selection_required: "請只選取一個片段。",
          stale_selection: "所選項目已不在已接受的時間軸中。",
          locked_track: "所選片段位於鎖定軌道。",
          playhead_unavailable: "播放頭目前無法使用。",
          playhead_outside_clip: "請將播放頭放在所選片段的嚴格內部。",
          clip_capacity: "時間軸已有 128 個片段。",
          command_limit: "一次編輯最多選取 32 個片段。",
          history_unavailable: "沒有可重做的歷程。",
          rebase_unavailable: "沒有可重新套用的遭拒屬性編輯。",
          cut_unavailable: "所選剪接點已不再相鄰。",
          source_range_unavailable: "此編輯點不對應已承認的來源影格。",
          empty_roll_side: "捲動編輯後兩側都必須至少保留一幀。",
        },
      },
      clip: "{name}，{start}–{end}，{duration}",
      titleClip: "標題",
      railLabel: "{name} · {start}–{end}",
      emptyLane: "將素材拖曳到這裡，或按縮圖上的「+」",
      selected: "已選取",
      trimStart: "修剪 {name} 的起點",
      snap: "邊緣吸附",
      trimEnd: "修剪 {name} 的終點",
      trimDraft: "{edge}邊緣 {delta} 個影格",
      trimInstructions:
        "方向鍵調整一個影格；Shift+方向鍵調整一格網格；Enter 確認；Escape 取消。",
      trimSubmitting: "正在送出修剪…",
      trimRejected: "修剪未套用；畫面顯示目前的時間軸。",
      trimAccepted: "修剪已接受。",
      trimReconciling: "修剪回應遺失；正在與已接受的時間軸對齊。",
      edgeStart: "起點",
      edgeEnd: "終點",
      zoomIn: "放大",
      zoomOut: "縮小",
      zoomFit: "符合時間軸",
      zoomSelection: "縮放至選取範圍",
      previousClip: "上一個片段",
      nextClip: "下一個片段",
      additiveSelection: "加入選取範圍",
      rangeSelection: "延伸選取範圍",
      clearSelection: "清除選取",
      selectAll: "選取所有片段",
      move: "移動片段或群組",
      moveEarlier: "向前移動一個格線步長",
      moveLater: "向後移動一個格線步長",
      moveTrackUp: "移至上一條軌道",
      moveTrackDown: "移至下一條軌道",
      apply: "套用",
      cancel: "取消",
      seekPreviousFrame: "向前定位一幀",
      seekNextFrame: "向後定位一幀",
      panEarlier: "向前平移時間軸",
      panLater: "向後平移時間軸",
      moveDraft: "移動草稿：{delta} 幀",
      insertDraft: "插入於第 {frame} 幀",
      insertRefused: "無法插入。{reason}",
      insertSubmitting: "正在插入片段…",
      insertAccepted: "已插入片段。",
      insertRejected: "未插入片段；目前顯示已接受的時間軸。",
      insertReconciling: "插入回應遺失；正在核對已接受的時間軸。",
      moveSubmitting: "正在提交移動…",
      moveAccepted: "已接受移動。",
      moveRejected: "未套用移動；目前顯示已接受的時間軸。",
      moveReconciling: "移動回應遺失；正在核對已接受的時間軸。",
      moveRefused: "無法移動。{reason}",
      moveRefusals: {
        group_limit: "一次最多移動 32 個片段。",
        locked_track: "軌道已鎖定。",
        overlap: "會與其他片段重疊。",
        bounds: "會超出時間軸的開頭或結尾。",
        incompatible_track: "該軌道無法放置此片段。",
        primary_track: "主軌只能放置原本就在主軌上的影片片段。",
        source_missing: "找不到片段所在的軌道。",
        target_exhaustion: "沒有可移入的軌道。",
        other: "無法在此移動。",
      },
      zoomStatus: "縮放 {zoom} 倍",
      zoomContinuous: "時間軸縮放",
      scroll: "時間軸檢視起點",
      playhead: "播放頭",
      playheadValue: "第 {frame} 影格",
      virtualized: "顯示第 {first} 至 {last} 條軌道，共 {total} 條",
      empty: "時間軸沒有片段。",
      loading: "正在載入時間軸…",
      absent:
        "沒有創作工作區。請從此脈絡開始，或從 Production 匯入已生成的片段。",
      revision: "已接受的時間軸修訂 {revision}",
      receipt: "已儲存最後一次編輯。",
      outcomeUnknownReading:
        "指令結果未知；正在重新讀取目前時間軸。未重送任何指令。",
      outcomeUnknownReadFailed:
        "指令結果未知，且無法重新讀取目前時間軸。未重送任何指令。",
      conflict: "工作區已變更或指令遭拒；目前顯示後端已接受的狀態。",
      pending: "正在套用指令…",
    },
    inspector: {
      title: "檢視器",
      noSelection: "選取片段或軌道以進行編輯。",
      draftDiscarded: "時間軸已變更，此區未送出的編輯已清除。",
      selection: "已選取 {count} 個片段",
      trackSection: "軌道",
      clipSection: "片段",
      rangeSection: "範圍",
      historySection: "歷程",
      apply: "套用",
      clipId: "片段",
      trackId: "軌道",
      assetId: "素材",
      newId: "新識別碼",
      kind: "類型",
      order: "順序",
      enabled: "啟用",
      locked: "鎖定",
      startFrame: "起始影格",
      durationFrames: "影格長度",
      sourceStartFrame: "來源起始影格",
      deltaFrames: "影格差量",
      edge: "邊緣",
      offsetFrames: "偏移影格",
      leftClip: "左側片段",
      rightClip: "右側片段",
      scopeTracks: "範圍軌道",
      opacity: "不透明度",
      blend: "混合",
      blendModes: { normal: "正常", multiply: "色彩增值", screen: "濾色" },
      transitionKind: "轉場",
      transitionKinds: { none: "無", cross_dissolve_v1: "交叉溶解" },
      transitionFrames: "轉場影格",
      effectKind: "效果",
      effectKinds: { none: "無", color_adjust_v1: "色彩調整" },
      brightness: "亮度",
      contrast: "對比",
      saturation: "飽和度",
      positionX: "位置 X",
      positionY: "位置 Y",
      scaleX: "縮放 X",
      scaleY: "縮放 Y",
      rotation: "旋轉",
      anchorX: "錨點 X",
      anchorY: "錨點 Y",
      cropLeft: "裁切左",
      cropTop: "裁切上",
      cropRight: "裁切右",
      cropBottom: "裁切下",
      unitName: "{label}（{unit}）",
      clipRange: "{start} – {end} · {duration}",
      seconds: "{seconds} 秒",
      textContent: "文字",
      fontAsset: "字型素材",
      fontSize: "大小（px）",
      fontWeight: "字重",
      fontWeights: { regular: "一般", bold: "粗體" },
      textColor: "顏色",
      volume: "音量",
      mute: "靜音",
      fadeIn: "淡入",
      fadeOut: "淡出",
      operations: {
        create_track: "新增軌道",
        remove_track: "移除軌道",
        reorder_track: "重新排序軌道",
        set_track_enabled: "軌道啟用",
        set_track_locked: "軌道鎖定",
        insert_asset_clip: "插入素材片段",
        insert_title_clip: "插入標題片段",
        replace_clip_asset: "替換片段素材",
        remove_clip: "移除片段",
        move_clip: "移動片段",
        move_group: "移動所選群組",
        trim_clip: "修剪片段",
        split_clip: "分割片段",
        merge_clips: "合併片段",
        insert_range: "插入範圍",
        overwrite_range: "覆寫範圍",
        ripple_delete: "漣漪刪除",
        ripple_trim: "漣漪修剪",
        roll_edit: "捲動編輯",
        slip_clip: "滑移片段",
        slide_clip: "滑動片段",
        set_clip_enabled: "片段啟用",
        set_visual_transform: "變形",
        set_crop: "裁切",
        set_opacity_blend: "不透明度與混合",
        set_text_content: "文字內容",
        set_text_style: "文字樣式",
        set_transition: "轉場",
        set_effect: "效果",
        set_clip_audio: "片段音訊",
        select_clips: "選取片段",
        undo: "復原",
        redo: "重做",
        rebase_transaction: "重新套用待處理編輯",
      },
      rebaseHint: "將最後一次遭拒的屬性編輯重新套用到目前已接受的時間軸。",
      rebaseUnavailable: "沒有可重新套用的待處理編輯。",
    },
    render: {
      title: "轉譯",
      unavailable: "此主機無法進行最終轉譯。",
      stale: "時間軸已變更；轉譯前請重新整理工作區。",
    },
    sequence: {
      title: "整部影片序列",
      planningLocation: "請在製作導演台規劃影片。關閉剪輯器即可回到那裡。",
      target: "目標長度（秒）",
      policy: "分段策略",
      policies: {
        auto_storyboard: "自動分鏡",
        fixed_5: "固定 5 秒",
        fixed_10: "固定 10 秒",
        fixed_12: "固定 12 秒",
        fixed_15: "固定 15 秒",
      },
      prepare: "準備規劃情境",
      prepared: "規劃情境已準備（修訂 {revision}）。",
      sourceAndTarget: "來源情境：{source} 秒。製作目標：{target} 秒。",
      segmentDurations: "片段要求與實際取樣時長",
      segmentDuration:
        "片段 {ordinal}：要求 {requested} 秒；實際取樣 {delivered} 秒（{frames} 影格）。",
      admitCanonical: "使用自動產生的分鏡",
      reviewStoryboard: "檢視分鏡列",
      admitReviewed: "採用已檢視的分鏡列",
      addRow: "新增鏡頭",
      removeRow: "移除鏡頭 {ordinal}",
      shotText: "鏡頭 {ordinal} 文字",
      shotStart: "起點（毫秒）",
      shotEnd: "終點（毫秒）",
      hardBoundary: "硬邊界",
      propose: "提議分段",
      proposal: "提議的計畫：{count} 個片段",
      proposalSegment: "{ordinal}. {mode} {seconds} 秒",
      blockers: "尚無法匯入",
      holds: "生成前",
      approveImport: "核准並匯入製作",
      createPlannedProject: "建立規劃專案",
      planningActions: "序列規劃操作",
      reviewActions: "分鏡列操作",
      scriptLabel: "分鏡腳本",
      scriptHint:
        "把整部影片寫成多個鏡頭：每個鏡頭以 [Shot 1]、[Shot 2] 依序開頭，或用空行分隔。若要自行指定切點，請為第一個之後的每個鏡頭加上起點，例如「[Shot 2] At 00:08,」；否則各鏡頭會平均分配目標長度。",
      scriptActions: "分鏡腳本操作",
      scriptLoadContext: "從情境載入鏡頭",
      scriptSplit: "將腳本切分為鏡頭",
      scriptSplitTimed: "{count} 個鏡頭，依腳本中的時間切分。",
      scriptSplitEven: "{count} 個鏡頭，平均分配 {target} 秒。",
      scriptErrors: {
        script_empty: "請先寫下影片的各個鏡頭。",
        script_shape:
          "無法讀取鏡頭。請從 [Shot 1] 開始依序編號，且每個鏡頭都要有自己的文字。",
        script_mixed_timing:
          "請為第一個之後的每個鏡頭都加上起點時間，或全部都不加。",
        script_time_range: "鏡頭的起點時間必須遞增，且落在目標長度之內。",
        script_too_many_shots:
          "鏡頭數量超過此目標長度可容納的數量。請減少鏡頭，或加長目標長度。",
        script_shot_too_long: "有鏡頭的文字太長，請縮短。",
        script_too_long: "腳本太長，請縮短。",
        script_context_empty:
          "情境提示詞中沒有可載入的鏡頭清單。請直接在這裡寫下鏡頭。",
      },
      readinessActions: "就緒狀態",
      describe: {
        prepare: "讀取目前的情境與製作專案，並將目標長度與分段策略綁定到它們。",
        admitCanonical:
          "使用最佳化提示詞中的分鏡，作為此計畫的鏡頭清單。適用於目標長度等於該單一片段長度的情況。",
        scriptLoadContext:
          "將情境提示詞描述的鏡頭複製到腳本框（不含其片段內的時間），讓你把它們延伸到整部影片。",
        scriptSplit:
          "以腳本中的鏡頭取代下方的分鏡列，並依目標長度配置時間。在你選擇採用已檢視的分鏡列之前，不會套用任何內容。",
        reviewStoryboard:
          "顯示分鏡列，讓你在採用前編輯每個鏡頭的文字、時間與硬邊界。",
        propose: "將分鏡拆成製作片段，並列出各片段的時長與模式供你檢視。",
        approveImport: "在製作專案中建立提議的片段。不會排入任何生成工作。",
        readiness: "檢查目前的主機、模型與擴充功能能否生成已匯入的計畫。",
        addRow: "在最後一列之後新增一個 5 秒的鏡頭。",
        admitReviewed: "使用你編輯過的分鏡列作為此計畫的分鏡。",
        createPlannedProject:
          "從目前的情境開始一個新的製作專案，讓此計畫可以匯入。",
      },
      imported: "計畫已匯入：{count} 個片段",
      stale: "製作工作區已變更；請重新準備規劃情境。",
      readiness: "檢查就緒狀態",
      readinessState: {
        idle: "尚未檢查就緒狀態",
        requesting: "正在檢查就緒狀態…",
        held: "尚未就緒，無法生成",
        ready: "可以生成",
        error: "無法檢查就緒狀態",
      },
      start: "生成已核准的序列",
      detach: "離開並讓目前片段繼續",
      detachHint:
        "只有目前片段可能完成；其餘片段會暫停，直到你回來並選擇繼續。",
      recoveryDeadline: "可恢復至 {deadline}；返回不會延長此期限。",
      resume: "繼續其餘片段",
      reattach: "重新連接執行中的序列",
      cancel: "取消序列",
      retrySegment: "重試片段 {ordinal}",
      refresh: "重新整理序列",
      state: {
        idle: "沒有執行中的序列",
        starting: "正在啟動序列…",
        attached_current_child: "正在執行目前片段",
        detach_ready: "目前片段已排入佇列；可以離開",
        detaching: "正在分離…",
        safe_to_leave: "可安全離開",
        reattach_reconciling: "正在重新連接…",
        current_segment_completed: "目前片段已完成；後續片段已暫停",
        current_segment_still_owned: "主機可能仍在處理；後續片段已暫停",
        paused_unknown_ownership: "片段狀態不明；後續片段已暫停",
        resume_ready: "可以繼續",
        recovery_unavailable_or_expired: "無法重新連接",
        finished: "序列已完成",
        failed: "序列因失敗而暫停",
      },
      slot: "{ordinal}. {state}",
      recoveryPointer: "可以重新連接先前的序列。",
      assembly: "組裝",
      assemble: "組裝序列",
      cancelAssembly: "取消組裝",
      retryAssembly: "重試組裝",
      assemblyState: "{state}（{completed} / {total}）",
      assemblyProfile:
        "組裝輸出正規化為 30 fps、48 kHz 立體聲；來源情境時長另計。",
      assemblyInputs: "由 {artifacts} 段片段影片與 {cuts} 個剪接點組成。",
      assemblyReceipt: "組裝完成並已驗證。",
      productionUnavailable: "製作工作區無法使用。",
      contextUnavailable: "情境工作區無法使用。",
    },
  },
  "zh-CN": {
    launcher: "打开完整剪辑器",
    launcherBusy: "正在打开完整剪辑器…",
    unsupported: "此浏览器无法使用完整剪辑器。",
    heading: "剪辑器工作区",
    barTitle: "剪辑器",
    dialogName: "剪辑器工作区",
    close: "关闭完整剪辑器",
    closeHint: "按 Escape 关闭完整剪辑器",
    resize: "调整工作区大小",
    resizeValue: "{width} × {height} 像素",
    surface: {
      opening: "正在打开完整剪辑器。",
      expanded: "完整剪辑器已就绪。",
      closing: "正在关闭完整剪辑器。",
      fallback: "合成监视器不可用；预览仅显示所选片段的来源。",
      monitorUnavailable: "合成监视器不可用。",
    },
    save: {
      region: "保存状态",
      loading: "加载中",
      saving: "正在保存…",
      notSaved: "未保存",
      checking: "正在确认…",
      unknown: "保存状态未知",
      failed: "编辑失败",
      refused: "编辑被拒",
      saved: "已保存",
      savedLive: "已保存。",
    },
    panes: {
      assets: "素材",
      text: "文字",
      sequence: "序列",
      inspector: "检查器",
      switcher: "素材区标签页",
      describe: {
        assets: "此工作区中的素材。",
        text: "在当前时间线添加标题。",
        sequence: "为 Production 项目规划、生成和组装整部视频。",
      },
    },
    shell: {
      regions: {
        bin: "素材区",
        monitor: "预览监视器",
        inspector: "检查器",
        timeline: "时间线",
      },
      splitters: {
        bin_monitor: "调整素材区与预览监视器大小",
        monitor_inspector: "调整预览监视器与检查器大小",
        top_timeline: "调整上方面板与时间线大小",
      },
      splitterClickHint:
        "点击分隔线左侧或上侧可向前移动一格；点击右侧或下侧可向后移动一格。双击可重置。",
      splitterValue: "{size} 像素",
      export: "导出",
      exportPanel: "导出最终视频",
    },
    summary: {
      title: "剪辑器项目",
      counts: "{tracks} 条轨道，{clips} 个片段",
      duration: "时长 {timecode}",
      contentExtent: "内容范围 {timecode}",
      editCapacity: "编辑容量 {timecode}",
      revision: "已接受的时间线修订 {revision}",
      notLoaded: "创作工作区已就绪。打开完整剪辑器以加载时间线。",
      absent: "尚无创作工作区。",
      released: "创作工作区已释放。",
      gone: "创作工作区已过期。",
      loading: "正在加载创作工作区…",
      pending: "正在应用指令…",
      start: "从此上下文开始创作",
      startUnavailable: "请先创建或打开 Context 工作区。",
      refresh: "刷新工作区",
      release: "释放工作区",
      confirmRelease: "确认释放",
      keep: "保留工作区",
      releaseWhileOpen: "关闭完整剪辑器后才能释放工作区。",
      actions: "工作区操作",
      describe: {
        start: "从当前的上下文创建创作工作区。打开完整剪辑器以编辑其时间线。",
        refresh: "重新读取已接受的工作区，不会更改任何内容。",
        release: "释放此工作区。下一步会请你确认。",
        confirmRelease: "立即释放工作区。之后无法再编辑其时间线。",
        keep: "保留工作区并取消释放。",
      },
    },
    assets: {
      title: "素材箱",
      empty: "此工作区没有素材。",
      noMatches: "没有符合条件的素材。",
      search: "搜索素材",
      sort: "排序素材",
      sortOriginal: "来源顺序",
      sortReverse: "反向顺序",
      filter: "筛选素材",
      filterAll: "所有素材",
      filterVideo: "视频",
      filterImage: "图片",
      filterAdded: "已添加到时间线",
      sortFilter: "排序与筛选",
      view: "视图",
      countLine: "{filter} · {count}",
      gridView: "网格视图",
      listView: "列表视图",
      card: "片段 {ordinal}",
      duration: "时长 {timecode}",
      durationUnavailable: "时长不可用",
      added: "已添加到时间线",
      pillAdded: "已添加",
      pillImported: "已导入",
      addToTimeline: "添加到时间线",
      addNamed: "将 {name} 添加到时间线",
      addTip: "追加到主视频轨末端",
      addPrimaryMissing: "无法添加：主视频轨不可用。",
      addPrimaryLocked: "无法添加：请先解锁主视频轨。",
      addTimingUnavailable: "无法添加：此素材没有可用的时间线时长。",
      addInsufficientCapacity: "无法添加：时间线剩余容量不足。",
      addRejected: "无法添加：片段无法追加到主视频轨。",
      addPending: "正在将片段添加到主视频轨末端…",
      addAccepted: "片段已添加到主视频轨末端。",
      addStaleRevision: "无法添加：时间线已更改，请检查最新内容后重试。",
      moreNamed: "{name} 的更多操作",
      moreActions: "更多片段操作",
      insertAtPlayhead: "在播放位置插入",
      overwriteAtPlayhead: "在播放位置覆盖",
      thumbnailLoading: "正在加载缩略图",
      thumbnailUnavailable: "缩略图不可用",
      textContent: "标题文字",
      font: "字体 {ordinal}",
      addTitle: "添加标题",
      titleRefusals: {
        busy: "请等待当前编辑完成。",
        missing_font: "请先选择可用字体，再添加标题。",
        invalid_content:
          "请使用 1–2,048 个字符、最多 32 行，且不要包含不支持的控制字符。",
        unavailable_frame: "请选择有效的播放位置。",
        insufficient_capacity: "请先设置大于零的编辑时长，再添加标题。",
        clip_limit: "已达 128 个片段的上限，请先移除一个片段。",
        track_limit:
          "八个轨道位置都已使用，请空出此位置的文字轨或移除一个轨道。",
      },
      kind: { video: "视频", image: "图片", font: "字体" },
      frames: "{frames} 个源帧",
      embeddedAudio: {
        present_bound: "内嵌音频",
        absent: "无内嵌音频",
        unavailable: "内嵌音频不可用",
        excluded_overlay_policy: "叠加层排除内嵌音频",
      },
      imported: "从制作导入",
      overlayAudioWarning: "插入叠加视频会排除其内嵌音轨。",
    },
    project: {
      title: "项目",
      resolution: "分辨率",
      frameRate: "帧率",
      duration: "时长",
      audio: "音频",
      export: "导出格式",
      size: "{width} × {height}",
      fps: "{fps} fps",
      kilohertz: "{rate} kHz",
      mono: "单声道",
      stereo: "立体声",
      channels: "{count} 声道",
      hint: "选择时间线上的片段或轨道，即可编辑其属性。",
    },
    monitor: {
      title: "监视器",
      header: "预览",
      emptyTitle: "时间线上还没有内容",
      unavailableTitle: "预览不可用",
      canvas: "合成监视器",
      browserPreviewOnly: "仅为浏览器预览；精确输出请渲染最终视频。",
      play: "播放",
      pause: "暂停",
      previousFrame: "上一帧",
      nextFrame: "下一帧",
      seek: "播放位置",
      seekValue: "第 {frame} 帧，共 {last}",
      frameUnavailable: "帧不可用",
      recover: "重试",
      transform: {
        move: "移动所选片段",
        north_west: "从左上缩放所选片段",
        north: "从上方缩放所选片段",
        north_east: "从右上缩放所选片段",
        east: "从右侧缩放所选片段",
        south_east: "从右下缩放所选片段",
        south: "从下方缩放所选片段",
        south_west: "从左下缩放所选片段",
        west: "从左侧缩放所选片段",
        rotate: "旋转所选片段",
      },
      transport: {
        label: "监视器播放控制",
        viewLabel: "监视器视图",
        playDescription: "从当前帧播放合成内容。",
        pauseDescription: "在当前帧暂停播放。",
        previousFrameDescription: "后退一帧。",
        nextFrameDescription: "前进一帧。",
        fit: "适应窗口",
        fitDescription: "将整个画面缩放到监视器内。",
        actual: "原始大小",
        actualDescription: "以一个合成像素对一个屏幕像素显示。",
        view: { fit: "适应窗口", actual: "100%" },
        fullscreen: "全屏",
        fullscreenDescription: "以全屏显示监视器；按 Escape 退出全屏。",
        fullscreenExit: "退出全屏",
        fullscreenExitDescription: "将监视器返回工作区。",
        fullscreenUnavailable: "此浏览器无法使用全屏。",
        fullscreenRefused: "全屏请求被拒绝。",
        timecode: "{current} / {total}",
        timecodeLabel: "时间码 {current}，共 {total}",
      },
      status: {
        closed: "监视器已关闭。",
        opening: "正在打开监视器。",
        paused: "监视器已暂停。",
        playing: "监视器播放中。",
        closing: "正在关闭监视器。",
        blocked: "监视器不可用：{reason}。",
        cleanup_pending: "监视器清理尚未完成。",
      },
      blocker: {
        source_unavailable: "来源不可用",
        canvas_unavailable: "画布不可用",
        invalid_contract: "不支持的合成内容",
        resource_limit: "超出资源上限",
      },
      unavailableReason: {
        source_unavailable: "无法读取片段的来源。",
        canvas_unavailable: "浏览器无法绘制画面。",
        invalid_contract: "此合成内容无法预览。",
        resource_limit: "预览所需资源超出浏览器上限。",
        cleanup_pending: "之前的预览仍在关闭中。",
      },
      selectedSourceOnly: "仅显示所选来源",
      selectedSourceNone: "选择含来源的片段以预览。",
      emptyHint: "按“媒体”中缩略图上的“+”，或将它拖到时间线，即可在此预览。",
    },
    audio: {
      title: "内嵌音频",
      policy:
        "内嵌源音频会跟随主视频的编辑。片段的音量、静音和淡入淡出可在其“音频”标签页设置；本版本不提供独立音轨。",
      state: {
        silent: "静音",
        following: "跟随主视频",
        seeking: "定位中",
        suspended: "已暂停",
        unavailable: "不可用",
      },
      owner: "拥有片段 {clip}",
      noOwner: "没有拥有片段",
    },
    timeline: {
      title: "时间线",
      menus: {
        trackMenu: "轨道菜单",
        clipMenu: "片段菜单",
        openTrack: "打开轨道菜单",
        openClip: "打开片段菜单",
        trimStartEarlier: "起点提前一帧",
        trimStartLater: "起点延后一帧",
        trimEndEarlier: "终点提前一帧",
        trimEndLater: "终点延后一帧",
      },
      grid: "时间线轨道",
      trackNames: { main: "主轨", overlay: "叠加 {n}", text: "文字 {n}" },
      trackToggles: { lock: "锁定 {name}", show: "显示 {name}" },
      trackKind: {
        primary_video: "主视频",
        video_overlay: "叠加视频",
        image_overlay: "叠加图片",
        text_overlay: "叠加文字",
      },
      trackActions: {
        lock: "锁定轨道",
        unlock: "解锁轨道",
        enable: "显示轨道",
        disable: "隐藏轨道",
      },
      toolbar: {
        label: "时间线工具",
        more: "更多时间线工具",
        withShortcut: "{text}（{keys}）",
        labels: {
          undo: "撤销",
          redo: "重做",
          split: "在播放头拆分",
          trimStart: "将起点修剪到播放头",
          trimEnd: "将终点修剪到播放头",
          delete: "删除",
          rippleDelete: "涟漪删除",
          snap: "吸附",
          ripple: "主轨涟漪",
          zoomOut: "缩小",
          zoomIn: "放大",
          fit: "适合时间线",
          rebase: "重新应用被拒编辑",
        },
        descriptions: {
          undo: "撤销最后一次已接受的时间线编辑。",
          redo: "重做下一次已接受的时间线编辑。",
          split: "在当前播放头拆分所选片段。",
          trimStart: "将所选片段的起点移到当前播放头。",
          trimEnd: "将所选片段的终点移到当前播放头。",
          delete: "在一次编辑中删除所选片段。",
          rippleDelete: "删除一个片段并移动其轨道上的后续片段。",
          snap: "将时间线编辑吸附到相邻边界。",
          ripple: "修剪或删除时移动同轨后续片段。",
          zoomOut: "显示更多时间线。",
          zoomIn: "放大以显示更多细节。",
          fit: "让整条时间线适合轨道宽度。",
          rebase: "将完全相同的被拒属性编辑重新应用到已接受时间线。",
          more: "打开较低优先级的时间线视图与选择工具。",
        },
        unavailable: {
          busy: "另一项时间线操作正在进行。",
          selection_required: "请至少选择一个片段。",
          single_selection_required: "请只选择一个片段。",
          stale_selection: "所选项目已不在已接受的时间线中。",
          locked_track: "所选片段位于锁定轨道。",
          playhead_unavailable: "播放头当前不可用。",
          playhead_outside_clip: "请将播放头放在所选片段的严格内部。",
          clip_capacity: "时间线已有 128 个片段。",
          command_limit: "一次编辑最多选择 32 个片段。",
          history_unavailable: "没有可重做的历史。",
          rebase_unavailable: "没有可重新应用的被拒属性编辑。",
          cut_unavailable: "所选剪切点已不再相邻。",
          source_range_unavailable: "此编辑点不对应已承认的来源帧。",
          empty_roll_side: "卷动编辑后两侧都必须至少保留一帧。",
        },
      },
      clip: "{name}，{start}–{end}，{duration}",
      titleClip: "标题",
      railLabel: "{name} · {start}–{end}",
      emptyLane: "将素材拖到这里，或按缩略图上的“+”",
      selected: "已选中",
      trimStart: "修剪 {name} 的起点",
      snap: "边缘吸附",
      trimEnd: "修剪 {name} 的终点",
      trimDraft: "{edge}边缘 {delta} 帧",
      trimInstructions:
        "方向键调整一帧；Shift+方向键调整一格网格；Enter 确认；Escape 取消。",
      trimSubmitting: "正在提交修剪…",
      trimRejected: "修剪未应用；当前显示的是最新时间线。",
      trimAccepted: "修剪已接受。",
      trimReconciling: "修剪响应丢失；正在与已接受的时间线对齐。",
      edgeStart: "起点",
      edgeEnd: "终点",
      zoomIn: "放大",
      zoomOut: "缩小",
      zoomFit: "适合时间线",
      zoomSelection: "缩放到所选片段",
      previousClip: "上一个片段",
      nextClip: "下一个片段",
      additiveSelection: "加入所选片段",
      rangeSelection: "扩展选择范围",
      clearSelection: "清除选择",
      selectAll: "选择所有片段",
      move: "移动片段或群组",
      moveEarlier: "向前移动一个网格步长",
      moveLater: "向后移动一个网格步长",
      moveTrackUp: "移至上一条轨道",
      moveTrackDown: "移至下一条轨道",
      apply: "应用",
      cancel: "取消",
      seekPreviousFrame: "向前定位一帧",
      seekNextFrame: "向后定位一帧",
      panEarlier: "向前平移时间线",
      panLater: "向后平移时间线",
      moveDraft: "移动草稿：{delta} 帧",
      insertDraft: "插入于第 {frame} 帧",
      insertRefused: "无法插入。{reason}",
      insertSubmitting: "正在插入片段…",
      insertAccepted: "已插入片段。",
      insertRejected: "未插入片段；当前显示已接受的时间线。",
      insertReconciling: "插入响应丢失；正在核对已接受的时间线。",
      moveSubmitting: "正在提交移动…",
      moveAccepted: "已接受移动。",
      moveRejected: "未应用移动；当前显示已接受的时间线。",
      moveReconciling: "移动响应丢失；正在核对已接受的时间线。",
      moveRefused: "无法移动。{reason}",
      moveRefusals: {
        group_limit: "一次最多移动 32 个片段。",
        locked_track: "轨道已锁定。",
        overlap: "会与其他片段重叠。",
        bounds: "会超出时间线的开头或结尾。",
        incompatible_track: "该轨道无法放置此片段。",
        primary_track: "主轨只能放置原本就在主轨上的视频片段。",
        source_missing: "找不到片段所在的轨道。",
        target_exhaustion: "没有可移入的轨道。",
        other: "无法在此移动。",
      },
      zoomStatus: "缩放 {zoom} 倍",
      zoomContinuous: "时间线缩放",
      scroll: "时间线视图起点",
      playhead: "播放头",
      playheadValue: "第 {frame} 帧",
      virtualized: "显示第 {first} 至 {last} 条轨道，共 {total} 条",
      empty: "时间线没有片段。",
      loading: "正在加载时间线…",
      absent:
        "没有创作工作区。请从此上下文开始，或从 Production 导入已生成的片段。",
      revision: "已接受的时间线修订 {revision}",
      receipt: "已保存最后一次编辑。",
      outcomeUnknownReading:
        "指令结果未知；正在重新读取当前时间线。未重发任何指令。",
      outcomeUnknownReadFailed:
        "指令结果未知，且无法重新读取当前时间线。未重发任何指令。",
      conflict: "工作区已变更或指令被拒；当前显示后端已接受的状态。",
      pending: "正在应用指令…",
    },
    inspector: {
      title: "检查器",
      noSelection: "选择片段或轨道以进行编辑。",
      draftDiscarded: "时间线已变更，此区未提交的编辑已清除。",
      selection: "已选中 {count} 个片段",
      trackSection: "轨道",
      clipSection: "片段",
      rangeSection: "范围",
      historySection: "历史",
      apply: "应用",
      clipId: "片段",
      trackId: "轨道",
      assetId: "素材",
      newId: "新标识符",
      kind: "类型",
      order: "顺序",
      enabled: "启用",
      locked: "锁定",
      startFrame: "起始帧",
      durationFrames: "帧长度",
      sourceStartFrame: "源起始帧",
      deltaFrames: "帧差量",
      edge: "边缘",
      offsetFrames: "偏移帧",
      leftClip: "左侧片段",
      rightClip: "右侧片段",
      scopeTracks: "范围轨道",
      opacity: "不透明度",
      blend: "混合",
      blendModes: { normal: "正常", multiply: "正片叠底", screen: "滤色" },
      transitionKind: "转场",
      transitionKinds: { none: "无", cross_dissolve_v1: "交叉溶解" },
      transitionFrames: "转场帧",
      effectKind: "效果",
      effectKinds: { none: "无", color_adjust_v1: "色彩调整" },
      brightness: "亮度",
      contrast: "对比度",
      saturation: "饱和度",
      positionX: "位置 X",
      positionY: "位置 Y",
      scaleX: "缩放 X",
      scaleY: "缩放 Y",
      rotation: "旋转",
      anchorX: "锚点 X",
      anchorY: "锚点 Y",
      cropLeft: "裁剪左",
      cropTop: "裁剪上",
      cropRight: "裁剪右",
      cropBottom: "裁剪下",
      unitName: "{label}（{unit}）",
      clipRange: "{start} – {end} · {duration}",
      seconds: "{seconds} 秒",
      textContent: "文字",
      fontAsset: "字体素材",
      fontSize: "大小（px）",
      fontWeight: "字重",
      fontWeights: { regular: "常规", bold: "粗体" },
      textColor: "颜色",
      volume: "音量",
      mute: "静音",
      fadeIn: "淡入",
      fadeOut: "淡出",
      operations: {
        create_track: "新增轨道",
        remove_track: "移除轨道",
        reorder_track: "重新排序轨道",
        set_track_enabled: "轨道启用",
        set_track_locked: "轨道锁定",
        insert_asset_clip: "插入素材片段",
        insert_title_clip: "插入标题片段",
        replace_clip_asset: "替换片段素材",
        remove_clip: "移除片段",
        move_clip: "移动片段",
        move_group: "移动所选组",
        trim_clip: "修剪片段",
        split_clip: "拆分片段",
        merge_clips: "合并片段",
        insert_range: "插入范围",
        overwrite_range: "覆盖范围",
        ripple_delete: "涟漪删除",
        ripple_trim: "涟漪修剪",
        roll_edit: "卷动编辑",
        slip_clip: "滑移片段",
        slide_clip: "滑动片段",
        set_clip_enabled: "片段启用",
        set_visual_transform: "变换",
        set_crop: "裁剪",
        set_opacity_blend: "不透明度与混合",
        set_text_content: "文字内容",
        set_text_style: "文字样式",
        set_transition: "转场",
        set_effect: "效果",
        set_clip_audio: "片段音频",
        select_clips: "选择片段",
        undo: "撤销",
        redo: "重做",
        rebase_transaction: "重新应用待处理编辑",
      },
      rebaseHint: "将最后一次被拒的属性编辑重新应用到当前已接受的时间线。",
      rebaseUnavailable: "没有可重新应用的待处理编辑。",
    },
    render: {
      title: "渲染",
      unavailable: "此主机无法进行最终渲染。",
      stale: "时间线已变更；渲染前请刷新工作区。",
    },
    sequence: {
      title: "整部视频序列",
      planningLocation: "请在制作导演台规划视频。关闭剪辑器即可回到那里。",
      target: "目标时长（秒）",
      policy: "分段策略",
      policies: {
        auto_storyboard: "自动分镜",
        fixed_5: "固定 5 秒",
        fixed_10: "固定 10 秒",
        fixed_12: "固定 12 秒",
        fixed_15: "固定 15 秒",
      },
      prepare: "准备规划上下文",
      prepared: "规划上下文已准备（修订 {revision}）。",
      sourceAndTarget: "来源上下文：{source} 秒。制作目标：{target} 秒。",
      segmentDurations: "片段要求与实际采样时长",
      segmentDuration:
        "片段 {ordinal}：要求 {requested} 秒；实际采样 {delivered} 秒（{frames} 帧）。",
      admitCanonical: "使用自动生成的分镜",
      reviewStoryboard: "查看分镜行",
      admitReviewed: "采用已查看的分镜行",
      addRow: "新增镜头",
      removeRow: "移除镜头 {ordinal}",
      shotText: "镜头 {ordinal} 文字",
      shotStart: "起点（毫秒）",
      shotEnd: "终点（毫秒）",
      hardBoundary: "硬边界",
      propose: "提议分段",
      proposal: "提议的计划：{count} 个片段",
      proposalSegment: "{ordinal}. {mode} {seconds} 秒",
      blockers: "暂无法导入",
      holds: "生成前",
      approveImport: "批准并导入制作",
      createPlannedProject: "创建规划项目",
      planningActions: "序列规划操作",
      reviewActions: "分镜行操作",
      scriptLabel: "分镜脚本",
      scriptHint:
        "把整部视频写成多个镜头：每个镜头以 [Shot 1]、[Shot 2] 依次开头，或用空行分隔。若要自行指定切点，请为第一个之后的每个镜头加上起点，例如“[Shot 2] At 00:08,”；否则各镜头会平均分配目标时长。",
      scriptActions: "分镜脚本操作",
      scriptLoadContext: "从上下文载入镜头",
      scriptSplit: "将脚本切分为镜头",
      scriptSplitTimed: "{count} 个镜头，按脚本中的时间切分。",
      scriptSplitEven: "{count} 个镜头，平均分配 {target} 秒。",
      scriptErrors: {
        script_empty: "请先写下视频的各个镜头。",
        script_shape:
          "无法读取镜头。请从 [Shot 1] 开始依次编号，且每个镜头都要有自己的文字。",
        script_mixed_timing:
          "请为第一个之后的每个镜头都加上起点时间，或全部都不加。",
        script_time_range: "镜头的起点时间必须递增，且落在目标时长之内。",
        script_too_many_shots:
          "镜头数量超过此目标时长可容纳的数量。请减少镜头，或加长目标时长。",
        script_shot_too_long: "有镜头的文字太长，请缩短。",
        script_too_long: "脚本太长，请缩短。",
        script_context_empty:
          "上下文提示词中没有可载入的镜头列表。请直接在这里写下镜头。",
      },
      readinessActions: "就绪状态",
      describe: {
        prepare:
          "读取当前的上下文与制作项目，并将目标时长与分段策略绑定到它们。",
        admitCanonical:
          "使用优化提示词中的分镜，作为此计划的镜头列表。适用于目标时长等于该单一片段时长的情况。",
        scriptLoadContext:
          "将上下文提示词描述的镜头复制到脚本框（不含其片段内的时间），让你把它们延伸到整部视频。",
        scriptSplit:
          "以脚本中的镜头取代下方的分镜行，并按目标时长配置时间。在你选择采用已查看的分镜行之前，不会套用任何内容。",
        reviewStoryboard:
          "显示分镜行，让你在采用前编辑每个镜头的文字、时间与硬边界。",
        propose: "将分镜拆成制作片段，并列出各片段的时长与模式供你查看。",
        approveImport: "在制作项目中创建提议的片段。不会排入任何生成任务。",
        readiness: "检查当前的主机、模型与扩展能否生成已导入的计划。",
        addRow: "在最后一行之后新增一个 5 秒的镜头。",
        admitReviewed: "使用你编辑过的分镜行作为此计划的分镜。",
        createPlannedProject:
          "从当前的上下文开始一个新的制作项目，让此计划可以导入。",
      },
      imported: "计划已导入：{count} 个片段",
      stale: "制作工作区已变更；请重新准备规划上下文。",
      readiness: "检查就绪状态",
      readinessState: {
        idle: "尚未检查就绪状态",
        requesting: "正在检查就绪状态…",
        held: "尚未就绪，无法生成",
        ready: "可以生成",
        error: "无法检查就绪状态",
      },
      start: "生成已批准的序列",
      detach: "离开并让当前片段继续",
      detachHint:
        "只有当前片段可能完成；其余片段会暂停，直到你回来并选择继续。",
      recoveryDeadline: "可恢复至 {deadline}；返回不会延长此期限。",
      resume: "继续其余片段",
      reattach: "重新连接运行中的序列",
      cancel: "取消序列",
      retrySegment: "重试片段 {ordinal}",
      refresh: "刷新序列",
      state: {
        idle: "没有运行中的序列",
        starting: "正在启动序列…",
        attached_current_child: "正在运行当前片段",
        detach_ready: "当前片段已排队；可以离开",
        detaching: "正在分离…",
        safe_to_leave: "可安全离开",
        reattach_reconciling: "正在重新连接…",
        current_segment_completed: "当前片段已完成；后续片段已暂停",
        current_segment_still_owned: "主机可能仍在处理；后续片段已暂停",
        paused_unknown_ownership: "片段状态未知；后续片段已暂停",
        resume_ready: "可以继续",
        recovery_unavailable_or_expired: "无法重新连接",
        finished: "序列已完成",
        failed: "序列因失败而暂停",
      },
      slot: "{ordinal}. {state}",
      recoveryPointer: "可以重新连接先前的序列。",
      assembly: "组装",
      assemble: "组装序列",
      cancelAssembly: "取消组装",
      retryAssembly: "重试组装",
      assemblyState: "{state}（{completed} / {total}）",
      assemblyProfile:
        "组装输出归一化为 30 fps、48 kHz 立体声；来源上下文时长另计。",
      assemblyInputs: "由 {artifacts} 段片段视频和 {cuts} 个剪切点组成。",
      assemblyReceipt: "组装完成并已验证。",
      productionUnavailable: "制作工作区不可用。",
      contextUnavailable: "上下文工作区不可用。",
    },
  },
} as const;

export type NleCopy = (typeof copy)["en"];

export function nleCopy(locale: Locale): NleCopy {
  return copy[locale] as unknown as NleCopy;
}

export function primaryAppendNotice(
  locale: Locale,
  code: PrimaryAppendNotice,
): string {
  const text = nleCopy(locale).assets;
  return {
    primary_missing: text.addPrimaryMissing,
    primary_locked: text.addPrimaryLocked,
    timing_unavailable: text.addTimingUnavailable,
    insufficient_capacity: text.addInsufficientCapacity,
    append_rejected: text.addRejected,
    pending: text.addPending,
    accepted: text.addAccepted,
    stale_revision: text.addStaleRevision,
  }[code];
}

export function fill(
  template: string,
  values: Readonly<Record<string, string | number>>,
): string {
  return template.replace(/\{(\w+)\}/gu, (match, key: string) =>
    key in values ? String(values[key]) : match,
  );
}
