"""Accepted native T2VA structural baseline: per-definition digests, never source text.

Generated by ``scripts/native_t2va_structure.py --host-root <root>
--revision b323a345 --emit-python``. Regenerate only for a newly
audited baseline; the classifier schema and this table are versioned together and both
are part of managed qualification compiler identity.
"""

SOURCE_REVISION = "b323a345bbbfb2f3a95b5b73b68eb7919a26515e"  # pragma: allowlist secret
SOURCE_BLOB = "0b1840e851c248f89e9920159c3c8237fa2e7186"  # pragma: allowlist secret
DEFINITIONS: tuple[tuple[str, str], ...] = (
    (
        "align_frame_count",
        "sha256:815144140ac0f0c20a42a56f1168ca3086485456a52b4cb552b1d84c362c5cd3",
    ),
    (
        "video_latent_t",
        "sha256:ddbe78607984329c205ec059fbad8114c5055e2a639c64cb7aceeb685316b0af",
    ),
    (
        "temporal_shape",
        "sha256:5632544f143ed19e2cda997c2493292317d42bd117c572a4cb0bdf0e1c60b86f",
    ),
    (
        "_empty_av_latent",
        "sha256:26fadedcd7bbed2d72094e8bb20ec2f4b4f3b125dad8eeba57f14092a6e3351d",
    ),
    (
        "EmptyMiniMaxH3LatentAV",
        "sha256:86eada1c51a9b09e633bb3404517041df858963f8873a914b042883f0005d717",
    ),
    (
        "MiniMaxH3SigmaShift",
        "sha256:6cb500867f47b7a0c6498d5cf564663d079ce1ac60bde13ab3a23b947248cbc6",
    ),
    (
        "MiniMaxH3ImageToVideo.define_schema",
        "sha256:48dbcd4e98c2b9afa141e3087700d870a385f9d901591489efe0b364abbb2857",
    ),
    (
        "MiniMaxH3ImageToVideo.execute",
        "sha256:d7477fcff0fe777655379476c4d1ff93b92caa5ba181adf7d72fad102241490c",
    ),
    (
        "MiniMaxH3ImageToVideo",
        "sha256:2e4cc7007bbbcc5727c4e0926955e61905cd8b4a0baab005eab2cde44e930c68",
    ),
)
CONSTANTS: tuple[tuple[str, str], ...] = (
    (
        "CANVAS_MULTIPLE",
        "sha256:4bbc40eb232c133e8bfac3e9ad8c165931f54112e6a4d551c7f95e085ab55b32",
    ),
    (
        "BASE_SHORT_EDGE",
        "sha256:383289f43aec04145db7c86df39ccb6565aaf082853fb99f94e3429cd7684556",
    ),
    (
        "MAX_PIXELS",
        "sha256:ff31347e6d92b88b7149ba78d54671ce195da18493b701b5900584aab950956c",
    ),
    (
        "REF_IMAGE_SHORT_EDGE",
        "sha256:a60810bf232af0fd71e3fb9a7bba6bdec75c7beb956760663bbb41bf3102ed10",
    ),
    (
        "FPS",
        "sha256:27b17d774039c50a8b7aef6aaf060822b36c06f89a6b813fce2ada32caaaf0a9",
    ),
    (
        "AUDIO_LATENT_FPS",
        "sha256:ddd3a27d187f8af6911bdaab2b520ec49bae831f1c30d48f923cc0440d2dff98",
    ),
)
PACKAGE_ROOTS: tuple[str, ...] = (
    "comfy",
    "nodes",
    "torch",
)
REQUIRED_IMPORTS: tuple[str, ...] = (
    "comfy.model_management",
    "comfy.model_sampling",
    "comfy.nested_tensor",
    "nodes",
    "torch",
)
FROM_BINDINGS: tuple[tuple[str, str], ...] = (
    (
        "io",
        "comfy_api.latest",
    ),
)
ENVELOPE_BINDINGS: tuple[tuple[str, str], ...] = (
    (
        "ComfyExtension",
        "comfy_api.latest",
    ),
)
PROTECTED_BUILTINS: tuple[str, ...] = (
    "classmethod",
    "hasattr",
    "max",
    "round",
    "staticmethod",
)
EXTERNAL_PATHS: tuple[str, ...] = (
    "comfy.model_management.intermediate_device",
    "comfy.model_sampling.CONST",
    "comfy.model_sampling.ModelSamplingAV",
    "comfy.nested_tensor.NestedTensor",
    "io.Clip.Input",
    "io.ComfyNode",
    "io.Conditioning.Output",
    "io.Float.Input",
    "io.Image.Input",
    "io.Int.Input",
    "io.Latent.Output",
    "io.Model.Input",
    "io.Model.Output",
    "io.NodeOutput",
    "io.Schema",
    "io.String.Input",
    "io.Vae.Input",
    "nodes.MAX_RESOLUTION",
    "torch.zeros",
)
