const fp = (value: string) => `sha256:${value.repeat(64)}`;

export function generationSequenceWire() {
  return {
    schema: "h3.context.generation_sequence_projection.v1",
    sequence_id: "sequence.1",
    sequence_fingerprint: fp("a"),
    state_fingerprint: fp("b"),
    workspace_id: "workspace.1",
    workspace_revision: 2,
    workspace_fingerprint: fp("c"),
    max_concurrency: 1,
    cancellation_requested: false,
    complete: false,
    correlation: { prompt_id: "prompt.1", execution_node_id: "node.1" },
    progress: [
      {
        job_id: "job.1",
        segment_id: "segment.1",
        ordinal: 1,
        state: "planned",
        attempt: 1,
        transaction_id: null,
        queue_prompt_id: null,
        host_owner_id: null,
        artifact_receipt_fingerprint: null,
        artifact_output_fingerprint: null,
        failure_code: null,
      },
    ],
    eligible_commands: [
      {
        job_id: "job.1",
        segment_id: "segment.1",
        ordinal: 1,
        task_mode: "t2va",
        source_id: "source.1",
        reference_ids: [],
        duration: {
          duration_milliseconds: 5167,
          frame_count: 124,
          delivered_milliseconds: 5167,
          snapped: false,
        },
        dependency_segment_ids: [],
        disposition: "dirty_self",
        reason_codes: ["producer_fingerprint_changed"],
        triggering_segment_ids: ["segment.1"],
        manifest_fingerprint: fp("d"),
        producer_fingerprint: fp("e"),
        native_binding_fingerprint: fp("f"),
        settings_fingerprint: fp("0"),
        graph_fingerprint: fp("1"),
        compiled_prompt_fingerprint: fp("2"),
        model_fingerprint: fp("3"),
        runtime_fingerprint: fp("4"),
        expected_format: "mp4",
        expected_shape: [720, 1280, 3],
        timeout_ms: 60_000,
        predecessor_receipt_fingerprint: null,
        predecessor_artifact_fingerprint: null,
        attempt: 1,
        transaction_id: "generation.command.1",
        fingerprint_domain: "output_producing_graph",
      },
    ],
  };
}
