"""Maintainer tool for the native T2VA structural admission baseline.

Reads native source bytes from an explicitly supplied ComfyUI checkout -- a Git revision through
``git show`` or the file on disk -- and never imports, compiles for execution or runs host code.
It imports repository pure code only and prints hashes, closed identifiers and counts, never
native source text.

Derive the manifest of an accepted revision (the committed baseline is regenerated from this)::

    python scripts/native_t2va_structure.py --host-root <root> --revision b323a345
    python scripts/native_t2va_structure.py --host-root <root> --revision b323a345 --emit-python

Classify a revision, or the disk file, with the production classifier::

    python scripts/native_t2va_structure.py --check --host-root <root> [--revision <rev>]

A disk or Git check is maintainer evidence only. It says nothing about which bytes a running host
loaded; runtime admission comes from the registered-module observer on the actual candidate.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import subprocess
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from comfyui_h3_context.core import native_t2va_structure as structure  # noqa: E402

NATIVE_SOURCE = "comfy_extras/nodes_minimax_h3.py"
AUDITED_DEFINITIONS = (
    "align_frame_count",
    "video_latent_t",
    "temporal_shape",
    "_empty_av_latent",
    "EmptyMiniMaxH3LatentAV",
    "MiniMaxH3SigmaShift",
    # Member rows first: a changed member is then named by its own row, not only by its class.
    structure.IMAGE_TO_VIDEO + ".define_schema",
    structure.IMAGE_TO_VIDEO + ".execute",
    structure.IMAGE_TO_VIDEO,
)


def git_blob(content: bytes) -> str:
    header = b"blob " + str(len(content)).encode("ascii") + b"\0"
    return hashlib.sha1(header + content, usedforsecurity=False).hexdigest()


def read_source(host_root: Path, revision: str | None) -> tuple[bytes, str | None]:
    """Return native bytes and the full revision they came from (None for the disk file)."""
    if revision is None:
        content = (host_root / NATIVE_SOURCE).read_bytes()
        return content, None
    full = (
        subprocess.check_output(
            ["git", "-C", str(host_root), "rev-parse", "--verify", revision + "^{commit}"]
        )
        .decode("ascii")
        .strip()
    )
    content = subprocess.check_output(
        ["git", "-C", str(host_root), "show", f"{full}:{NATIVE_SOURCE}"]
    )
    return content, full


def census(content: bytes) -> dict[str, int]:
    tree = ast.parse(content)
    pending: list[tuple[ast.AST, int]] = [(tree, 1)]
    nodes = depth = 0
    while pending:
        node, level = pending.pop()
        nodes += 1
        depth = max(depth, level)
        pending.extend((child, level + 1) for child in ast.iter_child_nodes(node))
    return {"bytes": len(content), "ast_nodes": nodes, "ast_depth": depth}


def render_python(manifest: structure.NativeT2VABaselineManifest) -> str:
    """Emit the baseline module exactly as `ruff format` leaves it, so regeneration is stable."""

    def text(value: str) -> str:
        return json.dumps(value)

    def pairs(items: tuple[tuple[str, str], ...]) -> str:
        return "".join(
            f"    (\n        {text(name)},\n        {text(value)},\n    ),\n"
            for name, value in items
        )

    def names(items: tuple[str, ...]) -> str:
        return "".join(f"    {text(name)},\n" for name in items)

    return (
        '"""Accepted native T2VA structural baseline: per-definition digests, never source text.\n'
        "\n"
        "Generated by ``scripts/native_t2va_structure.py --host-root <root>\n"
        f"--revision {manifest.source_revision[:8]} --emit-python``. Regenerate only for a newly\n"
        "audited baseline; the classifier schema and this table are versioned together and both\n"
        "are part of managed qualification compiler identity.\n"
        '"""\n'
        "\n"
        f"SOURCE_REVISION = {text(manifest.source_revision)}  # pragma: allowlist secret\n"
        f"SOURCE_BLOB = {text(manifest.source_blob)}  # pragma: allowlist secret\n"
        f"DEFINITIONS: tuple[tuple[str, str], ...] = (\n{pairs(manifest.definitions)})\n"
        f"CONSTANTS: tuple[tuple[str, str], ...] = (\n{pairs(manifest.constants)})\n"
        f"PACKAGE_ROOTS: tuple[str, ...] = (\n{names(manifest.package_roots)})\n"
        f"REQUIRED_IMPORTS: tuple[str, ...] = (\n{names(manifest.required_imports)})\n"
        f"FROM_BINDINGS: tuple[tuple[str, str], ...] = (\n{pairs(manifest.from_bindings)})\n"
        "ENVELOPE_BINDINGS: tuple[tuple[str, str], ...] = (\n"
        f"{pairs(manifest.envelope_bindings)})\n"
        f"PROTECTED_BUILTINS: tuple[str, ...] = (\n{names(manifest.protected_builtins)})\n"
        f"EXTERNAL_PATHS: tuple[str, ...] = (\n{names(manifest.external_paths)})\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("--host-root", required=True, type=Path)
    parser.add_argument("--revision", help="Git revision; omit with --check for the disk file")
    parser.add_argument("--check", action="store_true", help="classify with the production table")
    parser.add_argument("--emit-python", action="store_true", help="print the baseline module")
    args = parser.parse_args(argv)
    content, full = read_source(args.host_root, args.revision)
    blob = git_blob(content)
    facts: dict[str, object] = {
        "python": sys.version.split()[0],
        "classifier_schema": structure.NATIVE_T2VA_CLASSIFIER_SCHEMA,
        "subject": full or "disk",
        "source_blob": blob,
        **census(content),
    }
    if args.check:
        verdict = structure.classify_native_t2va_source(content)
        facts.update(
            {
                "mode": "check",
                "reason": verdict.reason.value,
                "check": verdict.check,
                "manifest_fingerprint": verdict.manifest_fingerprint,
                "production_admission": structure.is_production_admission(verdict),
                "scope": "maintainer disk/Git classification; not loaded-runtime evidence",
            }
        )
        print(json.dumps(facts, indent=2))
        return 0 if verdict.admitted else 1
    if full is None:
        parser.error("deriving a baseline requires --revision")
    manifest = structure.derive_manifest(
        content, source_revision=full, source_blob=blob, definitions=AUDITED_DEFINITIONS
    )
    if args.emit_python:
        # LF bytes: Windows text-mode stdout would emit CRLF and break the ruff-stable table.
        sys.stdout.buffer.write(render_python(manifest).encode("utf-8"))
        return 0
    facts.update(
        {
            "mode": "derive",
            "manifest": manifest.to_wire(),
            "manifest_fingerprint": manifest.fingerprint,
            "matches_committed": manifest == structure.PRODUCTION_MANIFEST,
        }
    )
    print(json.dumps(facts, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
